/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class __qsemaphore_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public __qsemaphore_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(__qsemaphore_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete___qsemaphore_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public __qsemaphore_t() {
    this(IdaJavaJNI.new___qsemaphore_t(), true);
  }

}
