/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class area_visitor2_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public area_visitor2_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(area_visitor2_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_area_visitor2_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int visit_area(area_t a) {
    return IdaJavaJNI.area_visitor2_t_visit_area(swigCPtr, this, area_t.getCPtr(a), a);
  }

}
