/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class area_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public area_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(area_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_area_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStartEA(long value) {
    IdaJavaJNI.area_t_startEA_set(swigCPtr, this, value);
  }

  public long getStartEA() {
    return IdaJavaJNI.area_t_startEA_get(swigCPtr, this);
  }

  public void setEndEA(long value) {
    IdaJavaJNI.area_t_endEA_set(swigCPtr, this, value);
  }

  public long getEndEA() {
    return IdaJavaJNI.area_t_endEA_get(swigCPtr, this);
  }

  public area_t() {
    this(IdaJavaJNI.new_area_t__SWIG_0(), true);
  }

  public area_t(long ea1, long ea2) {
    this(IdaJavaJNI.new_area_t__SWIG_1(ea1, ea2), true);
  }

  public int compare(area_t r) {
    return IdaJavaJNI.area_t_compare(swigCPtr, this, area_t.getCPtr(r), r);
  }

  public boolean __eq__(area_t r) {
    return IdaJavaJNI.area_t___eq__(swigCPtr, this, area_t.getCPtr(r), r);
  }

  public boolean __ne__(area_t r) {
    return IdaJavaJNI.area_t___ne__(swigCPtr, this, area_t.getCPtr(r), r);
  }

  public boolean __gt__(area_t r) {
    return IdaJavaJNI.area_t___gt__(swigCPtr, this, area_t.getCPtr(r), r);
  }

  public boolean __lt__(area_t r) {
    return IdaJavaJNI.area_t___lt__(swigCPtr, this, area_t.getCPtr(r), r);
  }

  public boolean contains(long ea) {
    return IdaJavaJNI.area_t_contains__SWIG_0(swigCPtr, this, ea);
  }

  public boolean contains(area_t r) {
    return IdaJavaJNI.area_t_contains__SWIG_1(swigCPtr, this, area_t.getCPtr(r), r);
  }

  public boolean overlaps(area_t r) {
    return IdaJavaJNI.area_t_overlaps(swigCPtr, this, area_t.getCPtr(r), r);
  }

  public void clear() {
    IdaJavaJNI.area_t_clear(swigCPtr, this);
  }

  public boolean empty() {
    return IdaJavaJNI.area_t_empty(swigCPtr, this);
  }

  public long size() {
    return IdaJavaJNI.area_t_size(swigCPtr, this);
  }

  public void intersect(area_t r) {
    IdaJavaJNI.area_t_intersect(swigCPtr, this, area_t.getCPtr(r), r);
  }

  public void extend(long ea) {
    IdaJavaJNI.area_t_extend(swigCPtr, this, ea);
  }

  public long print(String buf, long bufsize) {
    return IdaJavaJNI.area_t_print(swigCPtr, this, buf, bufsize);
  }

}
