/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class asm_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public asm_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(asm_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_asm_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFlag(long value) {
    IdaJavaJNI.asm_t_flag_set(swigCPtr, this, value);
  }

  public long getFlag() {
    return IdaJavaJNI.asm_t_flag_get(swigCPtr, this);
  }

  public void setUflag(int value) {
    IdaJavaJNI.asm_t_uflag_set(swigCPtr, this, value);
  }

  public int getUflag() {
    return IdaJavaJNI.asm_t_uflag_get(swigCPtr, this);
  }

  public String getName() {
    return IdaJavaJNI.asm_t_name_get(swigCPtr, this);
  }

  public void setHelp(int value) {
    IdaJavaJNI.asm_t_help_set(swigCPtr, this, value);
  }

  public int getHelp() {
    return IdaJavaJNI.asm_t_help_get(swigCPtr, this);
  }

  public SWIGTYPE_p_p_char getHeader() {
    long cPtr = IdaJavaJNI.asm_t_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_short getBadworks() {
    long cPtr = IdaJavaJNI.asm_t_badworks_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public String getOrigin() {
    return IdaJavaJNI.asm_t_origin_get(swigCPtr, this);
  }

  public String getEnd() {
    return IdaJavaJNI.asm_t_end_get(swigCPtr, this);
  }

  public String getCmnt() {
    return IdaJavaJNI.asm_t_cmnt_get(swigCPtr, this);
  }

  public void setAscsep(char value) {
    IdaJavaJNI.asm_t_ascsep_set(swigCPtr, this, value);
  }

  public char getAscsep() {
    return IdaJavaJNI.asm_t_ascsep_get(swigCPtr, this);
  }

  public void setAccsep(char value) {
    IdaJavaJNI.asm_t_accsep_set(swigCPtr, this, value);
  }

  public char getAccsep() {
    return IdaJavaJNI.asm_t_accsep_get(swigCPtr, this);
  }

  public String getEsccodes() {
    return IdaJavaJNI.asm_t_esccodes_get(swigCPtr, this);
  }

  public String getA_ascii() {
    return IdaJavaJNI.asm_t_a_ascii_get(swigCPtr, this);
  }

  public String getA_byte() {
    return IdaJavaJNI.asm_t_a_byte_get(swigCPtr, this);
  }

  public String getA_word() {
    return IdaJavaJNI.asm_t_a_word_get(swigCPtr, this);
  }

  public String getA_dword() {
    return IdaJavaJNI.asm_t_a_dword_get(swigCPtr, this);
  }

  public String getA_qword() {
    return IdaJavaJNI.asm_t_a_qword_get(swigCPtr, this);
  }

  public String getA_oword() {
    return IdaJavaJNI.asm_t_a_oword_get(swigCPtr, this);
  }

  public String getA_float() {
    return IdaJavaJNI.asm_t_a_float_get(swigCPtr, this);
  }

  public String getA_double() {
    return IdaJavaJNI.asm_t_a_double_get(swigCPtr, this);
  }

  public String getA_tbyte() {
    return IdaJavaJNI.asm_t_a_tbyte_get(swigCPtr, this);
  }

  public String getA_packreal() {
    return IdaJavaJNI.asm_t_a_packreal_get(swigCPtr, this);
  }

  public String getA_dups() {
    return IdaJavaJNI.asm_t_a_dups_get(swigCPtr, this);
  }

  public String getA_bss() {
    return IdaJavaJNI.asm_t_a_bss_get(swigCPtr, this);
  }

  public String getA_equ() {
    return IdaJavaJNI.asm_t_a_equ_get(swigCPtr, this);
  }

  public String getA_seg() {
    return IdaJavaJNI.asm_t_a_seg_get(swigCPtr, this);
  }

  public void setCheckarg_dispatch(SWIGTYPE_p_f_p_void_p_void_unsigned_char__bool value) {
    IdaJavaJNI.asm_t_checkarg_dispatch_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_void_unsigned_char__bool.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_void_unsigned_char__bool getCheckarg_dispatch() {
    long cPtr = IdaJavaJNI.asm_t_checkarg_dispatch_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_void_unsigned_char__bool(cPtr, false);
  }

  public SWIGTYPE_p_void get_UNUSED1_was_atomprefix() {
    long cPtr = IdaJavaJNI.asm_t__UNUSED1_was_atomprefix_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void get_UNUSED2_was_checkarg_operations() {
    long cPtr = IdaJavaJNI.asm_t__UNUSED2_was_checkarg_operations_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char getXlatAsciiOutput() {
    long cPtr = IdaJavaJNI.asm_t_XlatAsciiOutput_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public String getA_curip() {
    return IdaJavaJNI.asm_t_a_curip_get(swigCPtr, this);
  }

  public void setFunc_header(SWIGTYPE_p_f_p_func_t__void value) {
    IdaJavaJNI.asm_t_func_header_set(swigCPtr, this, SWIGTYPE_p_f_p_func_t__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_func_t__void getFunc_header() {
    long cPtr = IdaJavaJNI.asm_t_func_header_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_func_t__void(cPtr, false);
  }

  public void setFunc_footer(SWIGTYPE_p_f_p_func_t__void value) {
    IdaJavaJNI.asm_t_func_footer_set(swigCPtr, this, SWIGTYPE_p_f_p_func_t__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_func_t__void getFunc_footer() {
    long cPtr = IdaJavaJNI.asm_t_func_footer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_func_t__void(cPtr, false);
  }

  public String getA_public() {
    return IdaJavaJNI.asm_t_a_public_get(swigCPtr, this);
  }

  public String getA_weak() {
    return IdaJavaJNI.asm_t_a_weak_get(swigCPtr, this);
  }

  public String getA_extrn() {
    return IdaJavaJNI.asm_t_a_extrn_get(swigCPtr, this);
  }

  public String getA_comdef() {
    return IdaJavaJNI.asm_t_a_comdef_get(swigCPtr, this);
  }

  public void setGet_type_name(SWIGTYPE_p_f_unsigned_int_unsigned_int_p_char_size_t__int value) {
    IdaJavaJNI.asm_t_get_type_name_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_int_unsigned_int_p_char_size_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_int_unsigned_int_p_char_size_t__int getGet_type_name() {
    long cPtr = IdaJavaJNI.asm_t_get_type_name_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_int_unsigned_int_p_char_size_t__int(cPtr, false);
  }

  public String getA_align() {
    return IdaJavaJNI.asm_t_a_align_get(swigCPtr, this);
  }

  public void setLbrace(char value) {
    IdaJavaJNI.asm_t_lbrace_set(swigCPtr, this, value);
  }

  public char getLbrace() {
    return IdaJavaJNI.asm_t_lbrace_get(swigCPtr, this);
  }

  public void setRbrace(char value) {
    IdaJavaJNI.asm_t_rbrace_set(swigCPtr, this, value);
  }

  public char getRbrace() {
    return IdaJavaJNI.asm_t_rbrace_get(swigCPtr, this);
  }

  public String getA_mod() {
    return IdaJavaJNI.asm_t_a_mod_get(swigCPtr, this);
  }

  public String getA_band() {
    return IdaJavaJNI.asm_t_a_band_get(swigCPtr, this);
  }

  public String getA_bor() {
    return IdaJavaJNI.asm_t_a_bor_get(swigCPtr, this);
  }

  public String getA_xor() {
    return IdaJavaJNI.asm_t_a_xor_get(swigCPtr, this);
  }

  public String getA_bnot() {
    return IdaJavaJNI.asm_t_a_bnot_get(swigCPtr, this);
  }

  public String getA_shl() {
    return IdaJavaJNI.asm_t_a_shl_get(swigCPtr, this);
  }

  public String getA_shr() {
    return IdaJavaJNI.asm_t_a_shr_get(swigCPtr, this);
  }

  public String getA_sizeof_fmt() {
    return IdaJavaJNI.asm_t_a_sizeof_fmt_get(swigCPtr, this);
  }

  public void setFlag2(long value) {
    IdaJavaJNI.asm_t_flag2_set(swigCPtr, this, value);
  }

  public long getFlag2() {
    return IdaJavaJNI.asm_t_flag2_get(swigCPtr, this);
  }

  public String getCmnt2() {
    return IdaJavaJNI.asm_t_cmnt2_get(swigCPtr, this);
  }

  public String getLow8() {
    return IdaJavaJNI.asm_t_low8_get(swigCPtr, this);
  }

  public String getHigh8() {
    return IdaJavaJNI.asm_t_high8_get(swigCPtr, this);
  }

  public String getLow16() {
    return IdaJavaJNI.asm_t_low16_get(swigCPtr, this);
  }

  public String getHigh16() {
    return IdaJavaJNI.asm_t_high16_get(swigCPtr, this);
  }

  public String getA_include_fmt() {
    return IdaJavaJNI.asm_t_a_include_fmt_get(swigCPtr, this);
  }

  public String getA_vstruc_fmt() {
    return IdaJavaJNI.asm_t_a_vstruc_fmt_get(swigCPtr, this);
  }

  public String getA_3byte() {
    return IdaJavaJNI.asm_t_a_3byte_get(swigCPtr, this);
  }

  public String getA_rva() {
    return IdaJavaJNI.asm_t_a_rva_get(swigCPtr, this);
  }

}
