/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class auto_display_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public auto_display_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(auto_display_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_auto_display_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(int value) {
    IdaJavaJNI.auto_display_t_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return IdaJavaJNI.auto_display_t_type_get(swigCPtr, this);
  }

  public void setEa(long value) {
    IdaJavaJNI.auto_display_t_ea_set(swigCPtr, this, value);
  }

  public long getEa() {
    return IdaJavaJNI.auto_display_t_ea_get(swigCPtr, this);
  }

  public void setState(int value) {
    IdaJavaJNI.auto_display_t_state_set(swigCPtr, this, value);
  }

  public int getState() {
    return IdaJavaJNI.auto_display_t_state_get(swigCPtr, this);
  }

  public auto_display_t() {
    this(IdaJavaJNI.new_auto_display_t(), true);
  }

}
