/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class call_stack_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public call_stack_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(call_stack_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_call_stack_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDirty(boolean value) {
    IdaJavaJNI.call_stack_t_dirty_set(swigCPtr, this, value);
  }

  public boolean getDirty() {
    return IdaJavaJNI.call_stack_t_dirty_get(swigCPtr, this);
  }

  public call_stack_t() {
    this(IdaJavaJNI.new_call_stack_t(), true);
  }

}
