/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public enum choose_type_t {
  chtype_generic,
  chtype_idasgn,
  chtype_entry,
  chtype_name,
  chtype_stkvar_xref,
  chtype_xref,
  chtype_enum,
  chtype_enum_by_value,
  chtype_func,
  chtype_segm,
  chtype_segreg,
  chtype_struc,
  chtype_strpath,
  chtype_generic2,
  chtype_idatil;

  public final int swigValue() {
    return swigValue;
  }

  public static choose_type_t swigToEnum(int swigValue) {
    choose_type_t[] swigValues = choose_type_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (choose_type_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + choose_type_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private choose_type_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private choose_type_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private choose_type_t(choose_type_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

