/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class compiler_info_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public compiler_info_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(compiler_info_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_compiler_info_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(short value) {
    IdaJavaJNI.compiler_info_t_id_set(swigCPtr, this, value);
  }

  public short getId() {
    return IdaJavaJNI.compiler_info_t_id_get(swigCPtr, this);
  }

  public void setCm(short value) {
    IdaJavaJNI.compiler_info_t_cm_set(swigCPtr, this, value);
  }

  public short getCm() {
    return IdaJavaJNI.compiler_info_t_cm_get(swigCPtr, this);
  }

  public void setSize_i(short value) {
    IdaJavaJNI.compiler_info_t_size_i_set(swigCPtr, this, value);
  }

  public short getSize_i() {
    return IdaJavaJNI.compiler_info_t_size_i_get(swigCPtr, this);
  }

  public void setSize_b(short value) {
    IdaJavaJNI.compiler_info_t_size_b_set(swigCPtr, this, value);
  }

  public short getSize_b() {
    return IdaJavaJNI.compiler_info_t_size_b_get(swigCPtr, this);
  }

  public void setSize_e(short value) {
    IdaJavaJNI.compiler_info_t_size_e_set(swigCPtr, this, value);
  }

  public short getSize_e() {
    return IdaJavaJNI.compiler_info_t_size_e_get(swigCPtr, this);
  }

  public void setDefalign(short value) {
    IdaJavaJNI.compiler_info_t_defalign_set(swigCPtr, this, value);
  }

  public short getDefalign() {
    return IdaJavaJNI.compiler_info_t_defalign_get(swigCPtr, this);
  }

  public void setSize_s(short value) {
    IdaJavaJNI.compiler_info_t_size_s_set(swigCPtr, this, value);
  }

  public short getSize_s() {
    return IdaJavaJNI.compiler_info_t_size_s_get(swigCPtr, this);
  }

  public void setSize_l(short value) {
    IdaJavaJNI.compiler_info_t_size_l_set(swigCPtr, this, value);
  }

  public short getSize_l() {
    return IdaJavaJNI.compiler_info_t_size_l_get(swigCPtr, this);
  }

  public void setSize_ll(short value) {
    IdaJavaJNI.compiler_info_t_size_ll_set(swigCPtr, this, value);
  }

  public short getSize_ll() {
    return IdaJavaJNI.compiler_info_t_size_ll_get(swigCPtr, this);
  }

  public compiler_info_t() {
    this(IdaJavaJNI.new_compiler_info_t(), true);
  }

}
