/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class const_visitor_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public const_visitor_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(const_visitor_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_const_visitor_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int visit_const(long cid, long value) {
    return IdaJavaJNI.const_visitor_t_visit_const(swigCPtr, this, cid, value);
  }

}
