/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public enum custom_viewer_handler_id_t {
  CVH_USERDATA,
  CVH_KEYDOWN,
  CVH_POPUP,
  CVH_DBLCLICK,
  CVH_CURPOS,
  CVH_CLOSE,
  CVH_CLICK;

  public final int swigValue() {
    return swigValue;
  }

  public static custom_viewer_handler_id_t swigToEnum(int swigValue) {
    custom_viewer_handler_id_t[] swigValues = custom_viewer_handler_id_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (custom_viewer_handler_id_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + custom_viewer_handler_id_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private custom_viewer_handler_id_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private custom_viewer_handler_id_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private custom_viewer_handler_id_t(custom_viewer_handler_id_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

