/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class dbg_info_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public dbg_info_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(dbg_info_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_dbg_info_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPi(plugin_info_t value) {
    IdaJavaJNI.dbg_info_t_pi_set(swigCPtr, this, plugin_info_t.getCPtr(value), value);
  }

  public plugin_info_t getPi() {
    long cPtr = IdaJavaJNI.dbg_info_t_pi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new plugin_info_t(cPtr, false);
  }

  public void setDbg(debugger_t value) {
    IdaJavaJNI.dbg_info_t_dbg_set(swigCPtr, this, debugger_t.getCPtr(value), value);
  }

  public debugger_t getDbg() {
    long cPtr = IdaJavaJNI.dbg_info_t_dbg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new debugger_t(cPtr, false);
  }

  public dbg_info_t(plugin_info_t _pi, debugger_t _dbg) {
    this(IdaJavaJNI.new_dbg_info_t(plugin_info_t.getCPtr(_pi), _pi, debugger_t.getCPtr(_dbg), _dbg), true);
  }

}
