/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class debugger_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public debugger_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(debugger_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_debugger_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVersion(int value) {
    IdaJavaJNI.debugger_t_version_set(swigCPtr, this, value);
  }

  public int getVersion() {
    return IdaJavaJNI.debugger_t_version_get(swigCPtr, this);
  }

  public void setName(String value) {
    IdaJavaJNI.debugger_t_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return IdaJavaJNI.debugger_t_name_get(swigCPtr, this);
  }

  public void setId(int value) {
    IdaJavaJNI.debugger_t_id_set(swigCPtr, this, value);
  }

  public int getId() {
    return IdaJavaJNI.debugger_t_id_get(swigCPtr, this);
  }

  public void setProcessor(String value) {
    IdaJavaJNI.debugger_t_processor_set(swigCPtr, this, value);
  }

  public String getProcessor() {
    return IdaJavaJNI.debugger_t_processor_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    IdaJavaJNI.debugger_t_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return IdaJavaJNI.debugger_t_flags_get(swigCPtr, this);
  }

  public boolean is_remote() {
    return IdaJavaJNI.debugger_t_is_remote(swigCPtr, this);
  }

  public boolean must_have_hostname() {
    return IdaJavaJNI.debugger_t_must_have_hostname(swigCPtr, this);
  }

  public boolean can_continue_from_bpt() {
    return IdaJavaJNI.debugger_t_can_continue_from_bpt(swigCPtr, this);
  }

  public boolean may_disturb() {
    return IdaJavaJNI.debugger_t_may_disturb(swigCPtr, this);
  }

  public boolean is_safe() {
    return IdaJavaJNI.debugger_t_is_safe(swigCPtr, this);
  }

  public boolean use_sregs() {
    return IdaJavaJNI.debugger_t_use_sregs(swigCPtr, this);
  }

  public long cache_block_size() {
    return IdaJavaJNI.debugger_t_cache_block_size(swigCPtr, this);
  }

  public boolean use_memregs() {
    return IdaJavaJNI.debugger_t_use_memregs(swigCPtr, this);
  }

  public boolean may_take_exit_snapshot() {
    return IdaJavaJNI.debugger_t_may_take_exit_snapshot(swigCPtr, this);
  }

  public boolean virtual_threads() {
    return IdaJavaJNI.debugger_t_virtual_threads(swigCPtr, this);
  }

  public void setRegister_classes(SWIGTYPE_p_p_char value) {
    IdaJavaJNI.debugger_t_register_classes_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getRegister_classes() {
    long cPtr = IdaJavaJNI.debugger_t_register_classes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public void setRegister_classes_default(int value) {
    IdaJavaJNI.debugger_t_register_classes_default_set(swigCPtr, this, value);
  }

  public int getRegister_classes_default() {
    return IdaJavaJNI.debugger_t_register_classes_default_get(swigCPtr, this);
  }

  public void setRegisters(register_info_t value) {
    IdaJavaJNI.debugger_t_registers_set(swigCPtr, this, register_info_t.getCPtr(value), value);
  }

  public register_info_t getRegisters() {
    long cPtr = IdaJavaJNI.debugger_t_registers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new register_info_t(cPtr, false);
  }

  public void setRegisters_size(int value) {
    IdaJavaJNI.debugger_t_registers_size_set(swigCPtr, this, value);
  }

  public int getRegisters_size() {
    return IdaJavaJNI.debugger_t_registers_size_get(swigCPtr, this);
  }

  public void setMemory_page_size(int value) {
    IdaJavaJNI.debugger_t_memory_page_size_set(swigCPtr, this, value);
  }

  public int getMemory_page_size() {
    return IdaJavaJNI.debugger_t_memory_page_size_get(swigCPtr, this);
  }

  public void setBpt_bytes(SWIGTYPE_p_unsigned_char value) {
    IdaJavaJNI.debugger_t_bpt_bytes_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getBpt_bytes() {
    long cPtr = IdaJavaJNI.debugger_t_bpt_bytes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setBpt_size(int value) {
    IdaJavaJNI.debugger_t_bpt_size_set(swigCPtr, this, value);
  }

  public int getBpt_size() {
    return IdaJavaJNI.debugger_t_bpt_size_get(swigCPtr, this);
  }

  public void setInit_debugger(SWIGTYPE_p_f_p_q_const__char_int_p_q_const__char__bool value) {
    IdaJavaJNI.debugger_t_init_debugger_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__char_int_p_q_const__char__bool.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__char_int_p_q_const__char__bool getInit_debugger() {
    long cPtr = IdaJavaJNI.debugger_t_init_debugger_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_int_p_q_const__char__bool(cPtr, false);
  }

  public void setTerm_debugger(SWIGTYPE_p_f_void__bool value) {
    IdaJavaJNI.debugger_t_term_debugger_set(swigCPtr, this, SWIGTYPE_p_f_void__bool.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__bool getTerm_debugger() {
    long cPtr = IdaJavaJNI.debugger_t_term_debugger_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__bool(cPtr, false);
  }

  public void setProcess_get_info(SWIGTYPE_p_f_int_p_process_info_t__int value) {
    IdaJavaJNI.debugger_t_process_get_info_set(swigCPtr, this, SWIGTYPE_p_f_int_p_process_info_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_p_process_info_t__int getProcess_get_info() {
    long cPtr = IdaJavaJNI.debugger_t_process_get_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_p_process_info_t__int(cPtr, false);
  }

  public void setStart_process(SWIGTYPE_p_f_p_q_const__char_p_q_const__char_p_q_const__char_unsigned_int__int value) {
    IdaJavaJNI.debugger_t_start_process_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__char_p_q_const__char_p_q_const__char_unsigned_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__char_p_q_const__char_p_q_const__char_unsigned_int__int getStart_process() {
    long cPtr = IdaJavaJNI.debugger_t_start_process_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_p_q_const__char_p_q_const__char_unsigned_int__int(cPtr, false);
  }

  public void setAttach_process(SWIGTYPE_p_f_int_int__int value) {
    IdaJavaJNI.debugger_t_attach_process_set(swigCPtr, this, SWIGTYPE_p_f_int_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_int__int getAttach_process() {
    long cPtr = IdaJavaJNI.debugger_t_attach_process_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_int__int(cPtr, false);
  }

  public void setDetach_process(SWIGTYPE_p_f_void__int value) {
    IdaJavaJNI.debugger_t_detach_process_set(swigCPtr, this, SWIGTYPE_p_f_void__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__int getDetach_process() {
    long cPtr = IdaJavaJNI.debugger_t_detach_process_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__int(cPtr, false);
  }

  public void setRebase_if_required_to(SWIGTYPE_p_f_unsigned_int__void value) {
    IdaJavaJNI.debugger_t_rebase_if_required_to_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_int__void getRebase_if_required_to() {
    long cPtr = IdaJavaJNI.debugger_t_rebase_if_required_to_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_int__void(cPtr, false);
  }

  public void setPrepare_to_pause_process(SWIGTYPE_p_f_void__int value) {
    IdaJavaJNI.debugger_t_prepare_to_pause_process_set(swigCPtr, this, SWIGTYPE_p_f_void__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__int getPrepare_to_pause_process() {
    long cPtr = IdaJavaJNI.debugger_t_prepare_to_pause_process_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__int(cPtr, false);
  }

  public void setExit_process(SWIGTYPE_p_f_void__int value) {
    IdaJavaJNI.debugger_t_exit_process_set(swigCPtr, this, SWIGTYPE_p_f_void__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__int getExit_process() {
    long cPtr = IdaJavaJNI.debugger_t_exit_process_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__int(cPtr, false);
  }

  public void setGet_debug_event(SWIGTYPE_p_f_p_debug_event_t_bool__gdecode_t value) {
    IdaJavaJNI.debugger_t_get_debug_event_set(swigCPtr, this, SWIGTYPE_p_f_p_debug_event_t_bool__gdecode_t.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_debug_event_t_bool__gdecode_t getGet_debug_event() {
    long cPtr = IdaJavaJNI.debugger_t_get_debug_event_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_debug_event_t_bool__gdecode_t(cPtr, false);
  }

  public void setContinue_after_event(SWIGTYPE_p_f_p_q_const__debug_event_t__int value) {
    IdaJavaJNI.debugger_t_continue_after_event_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__debug_event_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__debug_event_t__int getContinue_after_event() {
    long cPtr = IdaJavaJNI.debugger_t_continue_after_event_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__debug_event_t__int(cPtr, false);
  }

  public void setSet_exception_info(SWIGTYPE_p_f_p_q_const__exception_info_t_int__void value) {
    IdaJavaJNI.debugger_t_set_exception_info_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__exception_info_t_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__exception_info_t_int__void getSet_exception_info() {
    long cPtr = IdaJavaJNI.debugger_t_set_exception_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__exception_info_t_int__void(cPtr, false);
  }

  public void setStopped_at_debug_event(SWIGTYPE_p_f_bool__void value) {
    IdaJavaJNI.debugger_t_stopped_at_debug_event_set(swigCPtr, this, SWIGTYPE_p_f_bool__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_bool__void getStopped_at_debug_event() {
    long cPtr = IdaJavaJNI.debugger_t_stopped_at_debug_event_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_bool__void(cPtr, false);
  }

  public void setThread_suspend(SWIGTYPE_p_f_int__int value) {
    IdaJavaJNI.debugger_t_thread_suspend_set(swigCPtr, this, SWIGTYPE_p_f_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int__int getThread_suspend() {
    long cPtr = IdaJavaJNI.debugger_t_thread_suspend_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int__int(cPtr, false);
  }

  public void setThread_continue(SWIGTYPE_p_f_int__int value) {
    IdaJavaJNI.debugger_t_thread_continue_set(swigCPtr, this, SWIGTYPE_p_f_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int__int getThread_continue() {
    long cPtr = IdaJavaJNI.debugger_t_thread_continue_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int__int(cPtr, false);
  }

  public void setThread_set_step(SWIGTYPE_p_f_int__int value) {
    IdaJavaJNI.debugger_t_thread_set_step_set(swigCPtr, this, SWIGTYPE_p_f_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int__int getThread_set_step() {
    long cPtr = IdaJavaJNI.debugger_t_thread_set_step_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int__int(cPtr, false);
  }

  public void setRead_registers(SWIGTYPE_p_f_int_int_p_regval_t__int value) {
    IdaJavaJNI.debugger_t_read_registers_set(swigCPtr, this, SWIGTYPE_p_f_int_int_p_regval_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_int_p_regval_t__int getRead_registers() {
    long cPtr = IdaJavaJNI.debugger_t_read_registers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_int_p_regval_t__int(cPtr, false);
  }

  public void setWrite_register(SWIGTYPE_p_f_int_int_p_q_const__regval_t__int value) {
    IdaJavaJNI.debugger_t_write_register_set(swigCPtr, this, SWIGTYPE_p_f_int_int_p_q_const__regval_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_int_p_q_const__regval_t__int getWrite_register() {
    long cPtr = IdaJavaJNI.debugger_t_write_register_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_int_p_q_const__regval_t__int(cPtr, false);
  }

  public void setThread_get_sreg_base(SWIGTYPE_p_f_int_int_p_unsigned_int__int value) {
    IdaJavaJNI.debugger_t_thread_get_sreg_base_set(swigCPtr, this, SWIGTYPE_p_f_int_int_p_unsigned_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_int_p_unsigned_int__int getThread_get_sreg_base() {
    long cPtr = IdaJavaJNI.debugger_t_thread_get_sreg_base_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_int_p_unsigned_int__int(cPtr, false);
  }

  public void setGet_memory_info(SWIGTYPE_p_f_r_qvector__memory_info_t____int value) {
    IdaJavaJNI.debugger_t_get_memory_info_set(swigCPtr, this, SWIGTYPE_p_f_r_qvector__memory_info_t____int.getCPtr(value));
  }

  public SWIGTYPE_p_f_r_qvector__memory_info_t____int getGet_memory_info() {
    long cPtr = IdaJavaJNI.debugger_t_get_memory_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_r_qvector__memory_info_t____int(cPtr, false);
  }

  public void setRead_memory(SWIGTYPE_p_f_unsigned_int_p_void_size_t__int value) {
    IdaJavaJNI.debugger_t_read_memory_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_int_p_void_size_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_int_p_void_size_t__int getRead_memory() {
    long cPtr = IdaJavaJNI.debugger_t_read_memory_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_int_p_void_size_t__int(cPtr, false);
  }

  public void setWrite_memory(SWIGTYPE_p_f_unsigned_int_p_q_const__void_size_t__int value) {
    IdaJavaJNI.debugger_t_write_memory_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_int_p_q_const__void_size_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_int_p_q_const__void_size_t__int getWrite_memory() {
    long cPtr = IdaJavaJNI.debugger_t_write_memory_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_int_p_q_const__void_size_t__int(cPtr, false);
  }

  public void setIs_ok_bpt(SWIGTYPE_p_f_int_unsigned_int_int__int value) {
    IdaJavaJNI.debugger_t_is_ok_bpt_set(swigCPtr, this, SWIGTYPE_p_f_int_unsigned_int_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_unsigned_int_int__int getIs_ok_bpt() {
    long cPtr = IdaJavaJNI.debugger_t_is_ok_bpt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_unsigned_int_int__int(cPtr, false);
  }

  public void setAdd_bpt(SWIGTYPE_p_f_int_unsigned_int_int__int value) {
    IdaJavaJNI.debugger_t_add_bpt_set(swigCPtr, this, SWIGTYPE_p_f_int_unsigned_int_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_unsigned_int_int__int getAdd_bpt() {
    long cPtr = IdaJavaJNI.debugger_t_add_bpt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_unsigned_int_int__int(cPtr, false);
  }

  public void setDel_bpt(SWIGTYPE_p_f_unsigned_int_p_q_const__unsigned_char_int__int value) {
    IdaJavaJNI.debugger_t_del_bpt_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_int_p_q_const__unsigned_char_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_int_p_q_const__unsigned_char_int__int getDel_bpt() {
    long cPtr = IdaJavaJNI.debugger_t_del_bpt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_int_p_q_const__unsigned_char_int__int(cPtr, false);
  }

  public void setOpen_file(SWIGTYPE_p_f_p_q_const__char_p_unsigned_int_bool__int value) {
    IdaJavaJNI.debugger_t_open_file_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__char_p_unsigned_int_bool__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__char_p_unsigned_int_bool__int getOpen_file() {
    long cPtr = IdaJavaJNI.debugger_t_open_file_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_p_unsigned_int_bool__int(cPtr, false);
  }

  public void setClose_file(SWIGTYPE_p_f_int__void value) {
    IdaJavaJNI.debugger_t_close_file_set(swigCPtr, this, SWIGTYPE_p_f_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_int__void getClose_file() {
    long cPtr = IdaJavaJNI.debugger_t_close_file_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int__void(cPtr, false);
  }

  public void setRead_file(SWIGTYPE_p_f_int_unsigned_int_p_void_size_t__int value) {
    IdaJavaJNI.debugger_t_read_file_set(swigCPtr, this, SWIGTYPE_p_f_int_unsigned_int_p_void_size_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_unsigned_int_p_void_size_t__int getRead_file() {
    long cPtr = IdaJavaJNI.debugger_t_read_file_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_unsigned_int_p_void_size_t__int(cPtr, false);
  }

  public void setMap_address(SWIGTYPE_p_f_unsigned_int_p_q_const__regval_t_int__unsigned_int value) {
    IdaJavaJNI.debugger_t_map_address_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_int_p_q_const__regval_t_int__unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_int_p_q_const__regval_t_int__unsigned_int getMap_address() {
    long cPtr = IdaJavaJNI.debugger_t_map_address_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_int_p_q_const__regval_t_int__unsigned_int(cPtr, false);
  }

  public void setSet_dbg_options(SWIGTYPE_p_f_p_q_const__char_int_p_q_const__void__p_char value) {
    IdaJavaJNI.debugger_t_set_dbg_options_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__char_int_p_q_const__void__p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__char_int_p_q_const__void__p_char getSet_dbg_options() {
    long cPtr = IdaJavaJNI.debugger_t_set_dbg_options_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_int_p_q_const__void__p_char(cPtr, false);
  }

  public void setGet_debmod_extensions(SWIGTYPE_p_f_void__p_void value) {
    IdaJavaJNI.debugger_t_get_debmod_extensions_set(swigCPtr, this, SWIGTYPE_p_f_void__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_void__p_void getGet_debmod_extensions() {
    long cPtr = IdaJavaJNI.debugger_t_get_debmod_extensions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_void__p_void(cPtr, false);
  }

  public void setUpdate_call_stack(SWIGTYPE_p_f_int_p_call_stack_t__bool value) {
    IdaJavaJNI.debugger_t_update_call_stack_set(swigCPtr, this, SWIGTYPE_p_f_int_p_call_stack_t__bool.getCPtr(value));
  }

  public SWIGTYPE_p_f_int_p_call_stack_t__bool getUpdate_call_stack() {
    long cPtr = IdaJavaJNI.debugger_t_update_call_stack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int_p_call_stack_t__bool(cPtr, false);
  }

  public void setAppcall(SWIGTYPE_p_f_unsigned_int_int_p_q_const__func_type_info_t_int_p_q_const__regobjs_t_p_relobj_t_p_regobjs_t_p__qstring__char___p_debug_event_t_int__unsigned_int value) {
    IdaJavaJNI.debugger_t_appcall_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_int_int_p_q_const__func_type_info_t_int_p_q_const__regobjs_t_p_relobj_t_p_regobjs_t_p__qstring__char___p_debug_event_t_int__unsigned_int.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_int_int_p_q_const__func_type_info_t_int_p_q_const__regobjs_t_p_relobj_t_p_regobjs_t_p__qstring__char___p_debug_event_t_int__unsigned_int getAppcall() {
    long cPtr = IdaJavaJNI.debugger_t_appcall_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_int_int_p_q_const__func_type_info_t_int_p_q_const__regobjs_t_p_relobj_t_p_regobjs_t_p__qstring__char___p_debug_event_t_int__unsigned_int(cPtr, false);
  }

  public void setCleanup_appcall(SWIGTYPE_p_f_int__int value) {
    IdaJavaJNI.debugger_t_cleanup_appcall_set(swigCPtr, this, SWIGTYPE_p_f_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_int__int getCleanup_appcall() {
    long cPtr = IdaJavaJNI.debugger_t_cleanup_appcall_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_int__int(cPtr, false);
  }

  public final static int default_port_number = 23946;
}
