/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class debug_event_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public debug_event_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(debug_event_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_debug_event_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public debug_event_t() {
    this(IdaJavaJNI.new_debug_event_t(), true);
  }

  public void setEid(event_id_t value) {
    IdaJavaJNI.debug_event_t_eid_set(swigCPtr, this, value.swigValue());
  }

  public event_id_t getEid() {
    return event_id_t.swigToEnum(IdaJavaJNI.debug_event_t_eid_get(swigCPtr, this));
  }

  public void setPid(int value) {
    IdaJavaJNI.debug_event_t_pid_set(swigCPtr, this, value);
  }

  public int getPid() {
    return IdaJavaJNI.debug_event_t_pid_get(swigCPtr, this);
  }

  public void setTid(int value) {
    IdaJavaJNI.debug_event_t_tid_set(swigCPtr, this, value);
  }

  public int getTid() {
    return IdaJavaJNI.debug_event_t_tid_get(swigCPtr, this);
  }

  public void setEa(long value) {
    IdaJavaJNI.debug_event_t_ea_set(swigCPtr, this, value);
  }

  public long getEa() {
    return IdaJavaJNI.debug_event_t_ea_get(swigCPtr, this);
  }

  public void setHandled(boolean value) {
    IdaJavaJNI.debug_event_t_handled_set(swigCPtr, this, value);
  }

  public boolean getHandled() {
    return IdaJavaJNI.debug_event_t_handled_get(swigCPtr, this);
  }

  public void setModinfo(module_info_t value) {
    IdaJavaJNI.debug_event_t_modinfo_set(swigCPtr, this, module_info_t.getCPtr(value), value);
  }

  public module_info_t getModinfo() {
    long cPtr = IdaJavaJNI.debug_event_t_modinfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new module_info_t(cPtr, false);
  }

  public void setExit_code(int value) {
    IdaJavaJNI.debug_event_t_exit_code_set(swigCPtr, this, value);
  }

  public int getExit_code() {
    return IdaJavaJNI.debug_event_t_exit_code_get(swigCPtr, this);
  }

  public void setInfo(String value) {
    IdaJavaJNI.debug_event_t_info_set(swigCPtr, this, value);
  }

  public String getInfo() {
    return IdaJavaJNI.debug_event_t_info_get(swigCPtr, this);
  }

  public void setBpt(e_breakpoint_t value) {
    IdaJavaJNI.debug_event_t_bpt_set(swigCPtr, this, e_breakpoint_t.getCPtr(value), value);
  }

  public e_breakpoint_t getBpt() {
    long cPtr = IdaJavaJNI.debug_event_t_bpt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new e_breakpoint_t(cPtr, false);
  }

  public void setExc(e_exception_t value) {
    IdaJavaJNI.debug_event_t_exc_set(swigCPtr, this, e_exception_t.getCPtr(value), value);
  }

  public e_exception_t getExc() {
    long cPtr = IdaJavaJNI.debug_event_t_exc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new e_exception_t(cPtr, false);
  }

  public long bpt_ea() {
    return IdaJavaJNI.debug_event_t_bpt_ea(swigCPtr, this);
  }

}
