/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public enum dem_mode_t {
  dem_mode16(0),
  dem_mode32(1),
  dem_mode64(2);

  public final int swigValue() {
    return swigValue;
  }

  public static dem_mode_t swigToEnum(int swigValue) {
    dem_mode_t[] swigValues = dem_mode_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (dem_mode_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + dem_mode_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private dem_mode_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private dem_mode_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private dem_mode_t(dem_mode_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

