/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class edge_typer_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public edge_typer_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(edge_typer_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_edge_typer_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void reset() {
    IdaJavaJNI.edge_typer_t_reset(swigCPtr, this);
  }

  public SWIGTYPE_p_edge_type_t edge_type(int i, int j) {
    return new SWIGTYPE_p_edge_type_t(IdaJavaJNI.edge_typer_t_edge_type__SWIG_0(swigCPtr, this, i, j), false);
  }

  public SWIGTYPE_p_edge_type_t edge_type(edge_t e) {
    return new SWIGTYPE_p_edge_type_t(IdaJavaJNI.edge_typer_t_edge_type__SWIG_1(swigCPtr, this, edge_t.getCPtr(e), e), false);
  }

}
