/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class edge_info_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public edge_info_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(edge_info_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_edge_info_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setColor(int value) {
    IdaJavaJNI.edge_info_t_color_set(swigCPtr, this, value);
  }

  public int getColor() {
    return IdaJavaJNI.edge_info_t_color_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    IdaJavaJNI.edge_info_t_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return IdaJavaJNI.edge_info_t_width_get(swigCPtr, this);
  }

  public void setSrcoff(int value) {
    IdaJavaJNI.edge_info_t_srcoff_set(swigCPtr, this, value);
  }

  public int getSrcoff() {
    return IdaJavaJNI.edge_info_t_srcoff_get(swigCPtr, this);
  }

  public void setDstoff(int value) {
    IdaJavaJNI.edge_info_t_dstoff_set(swigCPtr, this, value);
  }

  public int getDstoff() {
    return IdaJavaJNI.edge_info_t_dstoff_get(swigCPtr, this);
  }

  public void setLayout(pointseq_t value) {
    IdaJavaJNI.edge_info_t_layout_set(swigCPtr, this, pointseq_t.getCPtr(value), value);
  }

  public pointseq_t getLayout() {
    long cPtr = IdaJavaJNI.edge_info_t_layout_get(swigCPtr, this);
    return (cPtr == 0) ? null : new pointseq_t(cPtr, false);
  }

  public void reverse_layout() {
    IdaJavaJNI.edge_info_t_reverse_layout(swigCPtr, this);
  }

  public edge_info_t() {
    this(IdaJavaJNI.new_edge_info_t(), true);
  }

}
