/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class edge_layout_point_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public edge_layout_point_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(edge_layout_point_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_edge_layout_point_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPidx(int value) {
    IdaJavaJNI.edge_layout_point_t_pidx_set(swigCPtr, this, value);
  }

  public int getPidx() {
    return IdaJavaJNI.edge_layout_point_t_pidx_get(swigCPtr, this);
  }

  public void setE(edge_t value) {
    IdaJavaJNI.edge_layout_point_t_e_set(swigCPtr, this, edge_t.getCPtr(value), value);
  }

  public edge_t getE() {
    long cPtr = IdaJavaJNI.edge_layout_point_t_e_get(swigCPtr, this);
    return (cPtr == 0) ? null : new edge_t(cPtr, false);
  }

  public edge_layout_point_t() {
    this(IdaJavaJNI.new_edge_layout_point_t__SWIG_0(), true);
  }

  public edge_layout_point_t(edge_layout_point_t r) {
    this(IdaJavaJNI.new_edge_layout_point_t__SWIG_1(edge_layout_point_t.getCPtr(r), r), true);
  }

  public edge_layout_point_t(edge_t _e, int _pidx) {
    this(IdaJavaJNI.new_edge_layout_point_t__SWIG_2(edge_t.getCPtr(_e), _e, _pidx), true);
  }

  public int compare(edge_layout_point_t r) {
    return IdaJavaJNI.edge_layout_point_t_compare(swigCPtr, this, edge_layout_point_t.getCPtr(r), r);
  }

  public boolean __eq__(edge_layout_point_t r) {
    return IdaJavaJNI.edge_layout_point_t___eq__(swigCPtr, this, edge_layout_point_t.getCPtr(r), r);
  }

  public boolean __ne__(edge_layout_point_t r) {
    return IdaJavaJNI.edge_layout_point_t___ne__(swigCPtr, this, edge_layout_point_t.getCPtr(r), r);
  }

}
