/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class enum_const_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public enum_const_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(enum_const_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_enum_const_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTid(long value) {
    IdaJavaJNI.enum_const_t_tid_set(swigCPtr, this, value);
  }

  public long getTid() {
    return IdaJavaJNI.enum_const_t_tid_get(swigCPtr, this);
  }

  public void setSerial(short value) {
    IdaJavaJNI.enum_const_t_serial_set(swigCPtr, this, value);
  }

  public short getSerial() {
    return IdaJavaJNI.enum_const_t_serial_get(swigCPtr, this);
  }

  public enum_const_t() {
    this(IdaJavaJNI.new_enum_const_t(), true);
  }

}
