/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public enum event_id_t {
  NO_EVENT(0x00000000),
  PROCESS_START(0x00000001),
  PROCESS_EXIT(0x00000002),
  THREAD_START(0x00000004),
  THREAD_EXIT(0x00000008),
  BREAKPOINT(0x00000010),
  STEP(0x00000020),
  EXCEPTION(0x00000040),
  LIBRARY_LOAD(0x00000080),
  LIBRARY_UNLOAD(0x00000100),
  INFORMATION(0x00000200),
  SYSCALL(0x00000400),
  WINMESSAGE(0x00000800),
  PROCESS_ATTACH(0x00001000),
  PROCESS_DETACH(0x00002000),
  PROCESS_SUSPEND(0x00004000);

  public final int swigValue() {
    return swigValue;
  }

  public static event_id_t swigToEnum(int swigValue) {
    event_id_t[] swigValues = event_id_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (event_id_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + event_id_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private event_id_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private event_id_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private event_id_t(event_id_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

