/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class extfun_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public extfun_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(extfun_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_extfun_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    IdaJavaJNI.extfun_t_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return IdaJavaJNI.extfun_t_name_get(swigCPtr, this);
  }

  public void setFp(SWIGTYPE_p_f_p_idc_value_t_p_idc_value_t__error_t value) {
    IdaJavaJNI.extfun_t_fp_set(swigCPtr, this, SWIGTYPE_p_f_p_idc_value_t_p_idc_value_t__error_t.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_idc_value_t_p_idc_value_t__error_t getFp() {
    long cPtr = IdaJavaJNI.extfun_t_fp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_idc_value_t_p_idc_value_t__error_t(cPtr, false);
  }

  public void setArgs(String value) {
    IdaJavaJNI.extfun_t_args_set(swigCPtr, this, value);
  }

  public String getArgs() {
    return IdaJavaJNI.extfun_t_args_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    IdaJavaJNI.extfun_t_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return IdaJavaJNI.extfun_t_flags_get(swigCPtr, this);
  }

  public extfun_t() {
    this(IdaJavaJNI.new_extfun_t(), true);
  }

}
