/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class extlang_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public extlang_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(extlang_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_extlang_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSize(long value) {
    IdaJavaJNI.extlang_t_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return IdaJavaJNI.extlang_t_size_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    IdaJavaJNI.extlang_t_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return IdaJavaJNI.extlang_t_flags_get(swigCPtr, this);
  }

  public void setName(String value) {
    IdaJavaJNI.extlang_t_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return IdaJavaJNI.extlang_t_name_get(swigCPtr, this);
  }

  public void setCompile(SWIGTYPE_p_f_p_q_const__char_unsigned_int_p_q_const__char_p_char_size_t__bool value) {
    IdaJavaJNI.extlang_t_compile_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__char_unsigned_int_p_q_const__char_p_char_size_t__bool.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__char_unsigned_int_p_q_const__char_p_char_size_t__bool getCompile() {
    long cPtr = IdaJavaJNI.extlang_t_compile_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_unsigned_int_p_q_const__char_p_char_size_t__bool(cPtr, false);
  }

  public void setRun(SWIGTYPE_p_f_p_q_const__char_int_a___q_const__idc_value_t_p_idc_value_t_p_char_size_t__bool value) {
    IdaJavaJNI.extlang_t_run_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__char_int_a___q_const__idc_value_t_p_idc_value_t_p_char_size_t__bool.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__char_int_a___q_const__idc_value_t_p_idc_value_t_p_char_size_t__bool getRun() {
    long cPtr = IdaJavaJNI.extlang_t_run_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_int_a___q_const__idc_value_t_p_idc_value_t_p_char_size_t__bool(cPtr, false);
  }

  public void setCalcexpr(SWIGTYPE_p_f_unsigned_int_p_q_const__char_p_idc_value_t_p_char_size_t__bool value) {
    IdaJavaJNI.extlang_t_calcexpr_set(swigCPtr, this, SWIGTYPE_p_f_unsigned_int_p_q_const__char_p_idc_value_t_p_char_size_t__bool.getCPtr(value));
  }

  public SWIGTYPE_p_f_unsigned_int_p_q_const__char_p_idc_value_t_p_char_size_t__bool getCalcexpr() {
    long cPtr = IdaJavaJNI.extlang_t_calcexpr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_unsigned_int_p_q_const__char_p_idc_value_t_p_char_size_t__bool(cPtr, false);
  }

  public void setCompile_file(SWIGTYPE_p_f_p_q_const__char_p_char_size_t__bool value) {
    IdaJavaJNI.extlang_t_compile_file_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__char_p_char_size_t__bool.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__char_p_char_size_t__bool getCompile_file() {
    long cPtr = IdaJavaJNI.extlang_t_compile_file_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__char_p_char_size_t__bool(cPtr, false);
  }

  public void setFileext(String value) {
    IdaJavaJNI.extlang_t_fileext_set(swigCPtr, this, value);
  }

  public String getFileext() {
    return IdaJavaJNI.extlang_t_fileext_get(swigCPtr, this);
  }

}
