/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class fbase_reg_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public fbase_reg_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(fbase_reg_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_fbase_reg_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(long value) {
    IdaJavaJNI.fbase_reg_t_value_set(swigCPtr, this, value);
  }

  public long getValue() {
    return IdaJavaJNI.fbase_reg_t_value_get(swigCPtr, this);
  }

  public void setMinea(long value) {
    IdaJavaJNI.fbase_reg_t_minea_set(swigCPtr, this, value);
  }

  public long getMinea() {
    return IdaJavaJNI.fbase_reg_t_minea_get(swigCPtr, this);
  }

  public void setReg(short value) {
    IdaJavaJNI.fbase_reg_t_reg_set(swigCPtr, this, value);
  }

  public short getReg() {
    return IdaJavaJNI.fbase_reg_t_reg_get(swigCPtr, this);
  }

  public void setUnused(short value) {
    IdaJavaJNI.fbase_reg_t_unused_set(swigCPtr, this, value);
  }

  public short getUnused() {
    return IdaJavaJNI.fbase_reg_t_unused_get(swigCPtr, this);
  }

  public fbase_reg_t() {
    this(IdaJavaJNI.new_fbase_reg_t(), true);
  }

}
