/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class func_parent_iterator_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public func_parent_iterator_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(func_parent_iterator_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_func_parent_iterator_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public func_parent_iterator_t() {
    this(IdaJavaJNI.new_func_parent_iterator_t__SWIG_0(), true);
  }

  public func_parent_iterator_t(func_t _fnt) {
    this(IdaJavaJNI.new_func_parent_iterator_t__SWIG_1(func_t.getCPtr(_fnt), _fnt), true);
  }

  public boolean set(func_t _fnt) {
    return IdaJavaJNI.func_parent_iterator_t_set(swigCPtr, this, func_t.getCPtr(_fnt), _fnt);
  }

  public long parent() {
    return IdaJavaJNI.func_parent_iterator_t_parent(swigCPtr, this);
  }

  public boolean first() {
    return IdaJavaJNI.func_parent_iterator_t_first(swigCPtr, this);
  }

  public boolean last() {
    return IdaJavaJNI.func_parent_iterator_t_last(swigCPtr, this);
  }

  public boolean next() {
    return IdaJavaJNI.func_parent_iterator_t_next(swigCPtr, this);
  }

  public boolean prev() {
    return IdaJavaJNI.func_parent_iterator_t_prev(swigCPtr, this);
  }

  public void reset_fnt(func_t _fnt) {
    IdaJavaJNI.func_parent_iterator_t_reset_fnt(swigCPtr, this, func_t.getCPtr(_fnt), _fnt);
  }

}
