/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class func_item_iterator_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public func_item_iterator_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(func_item_iterator_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_func_item_iterator_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public func_item_iterator_t() {
    this(IdaJavaJNI.new_func_item_iterator_t__SWIG_0(), true);
  }

  public func_item_iterator_t(func_t pfn, long ea) {
    this(IdaJavaJNI.new_func_item_iterator_t__SWIG_1(func_t.getCPtr(pfn), pfn, ea), true);
  }

  public func_item_iterator_t(func_t pfn) {
    this(IdaJavaJNI.new_func_item_iterator_t__SWIG_2(func_t.getCPtr(pfn), pfn), true);
  }

  public boolean set(func_t pfn, long _ea) {
    return IdaJavaJNI.func_item_iterator_t_set__SWIG_0(swigCPtr, this, func_t.getCPtr(pfn), pfn, _ea);
  }

  public boolean set(func_t pfn) {
    return IdaJavaJNI.func_item_iterator_t_set__SWIG_1(swigCPtr, this, func_t.getCPtr(pfn), pfn);
  }

  public boolean set_range(long ea1, long ea2) {
    return IdaJavaJNI.func_item_iterator_t_set_range(swigCPtr, this, ea1, ea2);
  }

  public boolean first() {
    return IdaJavaJNI.func_item_iterator_t_first(swigCPtr, this);
  }

  public boolean last() {
    return IdaJavaJNI.func_item_iterator_t_last(swigCPtr, this);
  }

  public long current() {
    return IdaJavaJNI.func_item_iterator_t_current(swigCPtr, this);
  }

  public area_t chunk() {
    return new area_t(IdaJavaJNI.func_item_iterator_t_chunk(swigCPtr, this), false);
  }

  public boolean next(SWIGTYPE_p_f_unsigned_int_p_void__bool func, SWIGTYPE_p_void ud) {
    return IdaJavaJNI.func_item_iterator_t_next(swigCPtr, this, SWIGTYPE_p_f_unsigned_int_p_void__bool.getCPtr(func), SWIGTYPE_p_void.getCPtr(ud));
  }

  public boolean prev(SWIGTYPE_p_f_unsigned_int_p_void__bool func, SWIGTYPE_p_void ud) {
    return IdaJavaJNI.func_item_iterator_t_prev(swigCPtr, this, SWIGTYPE_p_f_unsigned_int_p_void__bool.getCPtr(func), SWIGTYPE_p_void.getCPtr(ud));
  }

  public boolean next_addr() {
    return IdaJavaJNI.func_item_iterator_t_next_addr(swigCPtr, this);
  }

  public boolean next_head() {
    return IdaJavaJNI.func_item_iterator_t_next_head(swigCPtr, this);
  }

  public boolean next_code() {
    return IdaJavaJNI.func_item_iterator_t_next_code(swigCPtr, this);
  }

  public boolean next_data() {
    return IdaJavaJNI.func_item_iterator_t_next_data(swigCPtr, this);
  }

  public boolean next_not_tail() {
    return IdaJavaJNI.func_item_iterator_t_next_not_tail(swigCPtr, this);
  }

  public boolean prev_addr() {
    return IdaJavaJNI.func_item_iterator_t_prev_addr(swigCPtr, this);
  }

  public boolean prev_head() {
    return IdaJavaJNI.func_item_iterator_t_prev_head(swigCPtr, this);
  }

  public boolean prev_code() {
    return IdaJavaJNI.func_item_iterator_t_prev_code(swigCPtr, this);
  }

  public boolean prev_data() {
    return IdaJavaJNI.func_item_iterator_t_prev_data(swigCPtr, this);
  }

  public boolean prev_not_tail() {
    return IdaJavaJNI.func_item_iterator_t_prev_not_tail(swigCPtr, this);
  }

  public boolean decode_prev_insn() {
    return IdaJavaJNI.func_item_iterator_t_decode_prev_insn(swigCPtr, this);
  }

  public boolean decode_preceding_insn(SWIGTYPE_p_qvectorT_unsigned_int_t visited, SWIGTYPE_p_bool p_farref) {
    return IdaJavaJNI.func_item_iterator_t_decode_preceding_insn(swigCPtr, this, SWIGTYPE_p_qvectorT_unsigned_int_t.getCPtr(visited), SWIGTYPE_p_bool.getCPtr(p_farref));
  }

}
