/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public enum gdecode_t {
  GDE_ERROR(-1),
  GDE_NO_EVENT,
  GDE_ONE_EVENT,
  GDE_MANY_EVENTS;

  public final int swigValue() {
    return swigValue;
  }

  public static gdecode_t swigToEnum(int swigValue) {
    gdecode_t[] swigValues = gdecode_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (gdecode_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + gdecode_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private gdecode_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private gdecode_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private gdecode_t(gdecode_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

