/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class graph_path_visitor_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public graph_path_visitor_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(graph_path_visitor_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_graph_path_visitor_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPath(SWIGTYPE_p_intseq_t value) {
    IdaJavaJNI.graph_path_visitor_t_path_set(swigCPtr, this, SWIGTYPE_p_intseq_t.getCPtr(value));
  }

  public SWIGTYPE_p_intseq_t getPath() {
    return new SWIGTYPE_p_intseq_t(IdaJavaJNI.graph_path_visitor_t_path_get(swigCPtr, this), true);
  }

  public void setPrune(boolean value) {
    IdaJavaJNI.graph_path_visitor_t_prune_set(swigCPtr, this, value);
  }

  public boolean getPrune() {
    return IdaJavaJNI.graph_path_visitor_t_prune_get(swigCPtr, this);
  }

  public int walk_forward(int arg0) {
    return IdaJavaJNI.graph_path_visitor_t_walk_forward(swigCPtr, this, arg0);
  }

  public int walk_backward(int arg0) {
    return IdaJavaJNI.graph_path_visitor_t_walk_backward(swigCPtr, this, arg0);
  }

  public graph_path_visitor_t() {
    this(IdaJavaJNI.new_graph_path_visitor_t(), true);
  }

}
