/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class graph_node_visitor_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public graph_node_visitor_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(graph_node_visitor_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_graph_node_visitor_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void reinit() {
    IdaJavaJNI.graph_node_visitor_t_reinit(swigCPtr, this);
  }

  public void set_visited(int n) {
    IdaJavaJNI.graph_node_visitor_t_set_visited(swigCPtr, this, n);
  }

  public boolean is_visited(int n) {
    return IdaJavaJNI.graph_node_visitor_t_is_visited(swigCPtr, this, n);
  }

  public int visit_node(int arg0) {
    return IdaJavaJNI.graph_node_visitor_t_visit_node(swigCPtr, this, arg0);
  }

  public boolean is_forbidden_edge(int arg0, int arg1) {
    return IdaJavaJNI.graph_node_visitor_t_is_forbidden_edge(swigCPtr, this, arg0, arg1);
  }

  public graph_node_visitor_t() {
    this(IdaJavaJNI.new_graph_node_visitor_t(), true);
  }

}
