/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class hidden_area_t extends area_t {
  private long swigCPtr;

  public hidden_area_t(long cPtr, boolean cMemoryOwn) {
    super(IdaJavaJNI.hidden_area_t_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(hidden_area_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_hidden_area_t(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setDescription(String value) {
    IdaJavaJNI.hidden_area_t_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return IdaJavaJNI.hidden_area_t_description_get(swigCPtr, this);
  }

  public void setHeader(String value) {
    IdaJavaJNI.hidden_area_t_header_set(swigCPtr, this, value);
  }

  public String getHeader() {
    return IdaJavaJNI.hidden_area_t_header_get(swigCPtr, this);
  }

  public void setFooter(String value) {
    IdaJavaJNI.hidden_area_t_footer_set(swigCPtr, this, value);
  }

  public String getFooter() {
    return IdaJavaJNI.hidden_area_t_footer_get(swigCPtr, this);
  }

  public void setVisible(boolean value) {
    IdaJavaJNI.hidden_area_t_visible_set(swigCPtr, this, value);
  }

  public boolean getVisible() {
    return IdaJavaJNI.hidden_area_t_visible_get(swigCPtr, this);
  }

  public void setColor(long value) {
    IdaJavaJNI.hidden_area_t_color_set(swigCPtr, this, value);
  }

  public long getColor() {
    return IdaJavaJNI.hidden_area_t_color_get(swigCPtr, this);
  }

  public hidden_area_t() {
    this(IdaJavaJNI.new_hidden_area_t(), true);
  }

}
