/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class idadll_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public idadll_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(idadll_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_idadll_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDllinfo(SWIGTYPE_p_p_void value) {
    IdaJavaJNI.idadll_t_dllinfo_set(swigCPtr, this, SWIGTYPE_p_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_p_void getDllinfo() {
    long cPtr = IdaJavaJNI.idadll_t_dllinfo_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public void setEntry(SWIGTYPE_p_void value) {
    IdaJavaJNI.idadll_t_entry_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getEntry() {
    long cPtr = IdaJavaJNI.idadll_t_entry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public idadll_t() {
    this(IdaJavaJNI.new_idadll_t(), true);
  }

  public boolean is_loaded() {
    return IdaJavaJNI.idadll_t_is_loaded(swigCPtr, this);
  }

}
