/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class idainfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public idainfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(idainfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_idainfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTag(String value) {
    IdaJavaJNI.idainfo_tag_set(swigCPtr, this, value);
  }

  public String getTag() {
    return IdaJavaJNI.idainfo_tag_get(swigCPtr, this);
  }

  public void setVersion(int value) {
    IdaJavaJNI.idainfo_version_set(swigCPtr, this, value);
  }

  public int getVersion() {
    return IdaJavaJNI.idainfo_version_get(swigCPtr, this);
  }

  public void setProcName(String value) {
    IdaJavaJNI.idainfo_procName_set(swigCPtr, this, value);
  }

  public String getProcName() {
    return IdaJavaJNI.idainfo_procName_get(swigCPtr, this);
  }

  public String get_proc_name(String buf) {
    return IdaJavaJNI.idainfo_get_proc_name(swigCPtr, this, buf);
  }

  public void setLflags(short value) {
    IdaJavaJNI.idainfo_lflags_set(swigCPtr, this, value);
  }

  public short getLflags() {
    return IdaJavaJNI.idainfo_lflags_get(swigCPtr, this);
  }

  public boolean is_32bit() {
    return IdaJavaJNI.idainfo_is_32bit(swigCPtr, this);
  }

  public boolean is_64bit() {
    return IdaJavaJNI.idainfo_is_64bit(swigCPtr, this);
  }

  public boolean is_snapshot() {
    return IdaJavaJNI.idainfo_is_snapshot(swigCPtr, this);
  }

  public void setDemnames(short value) {
    IdaJavaJNI.idainfo_demnames_set(swigCPtr, this, value);
  }

  public short getDemnames() {
    return IdaJavaJNI.idainfo_demnames_get(swigCPtr, this);
  }

  public short get_demname_form() {
    return IdaJavaJNI.idainfo_get_demname_form(swigCPtr, this);
  }

  public void setFiletype(int value) {
    IdaJavaJNI.idainfo_filetype_set(swigCPtr, this, value);
  }

  public int getFiletype() {
    return IdaJavaJNI.idainfo_filetype_get(swigCPtr, this);
  }

  public boolean like_binary() {
    return IdaJavaJNI.idainfo_like_binary(swigCPtr, this);
  }

  public void setFcoresiz(long value) {
    IdaJavaJNI.idainfo_fcoresiz_set(swigCPtr, this, value);
  }

  public long getFcoresiz() {
    return IdaJavaJNI.idainfo_fcoresiz_get(swigCPtr, this);
  }

  public void setCorestart(long value) {
    IdaJavaJNI.idainfo_corestart_set(swigCPtr, this, value);
  }

  public long getCorestart() {
    return IdaJavaJNI.idainfo_corestart_get(swigCPtr, this);
  }

  public void setOstype(int value) {
    IdaJavaJNI.idainfo_ostype_set(swigCPtr, this, value);
  }

  public int getOstype() {
    return IdaJavaJNI.idainfo_ostype_get(swigCPtr, this);
  }

  public void setApptype(int value) {
    IdaJavaJNI.idainfo_apptype_set(swigCPtr, this, value);
  }

  public int getApptype() {
    return IdaJavaJNI.idainfo_apptype_get(swigCPtr, this);
  }

  public void setStartSP(long value) {
    IdaJavaJNI.idainfo_startSP_set(swigCPtr, this, value);
  }

  public long getStartSP() {
    return IdaJavaJNI.idainfo_startSP_get(swigCPtr, this);
  }

  public void setAf(int value) {
    IdaJavaJNI.idainfo_af_set(swigCPtr, this, value);
  }

  public int getAf() {
    return IdaJavaJNI.idainfo_af_get(swigCPtr, this);
  }

  public void setStartIP(long value) {
    IdaJavaJNI.idainfo_startIP_set(swigCPtr, this, value);
  }

  public long getStartIP() {
    return IdaJavaJNI.idainfo_startIP_get(swigCPtr, this);
  }

  public void setBeginEA(long value) {
    IdaJavaJNI.idainfo_beginEA_set(swigCPtr, this, value);
  }

  public long getBeginEA() {
    return IdaJavaJNI.idainfo_beginEA_get(swigCPtr, this);
  }

  public void setMinEA(long value) {
    IdaJavaJNI.idainfo_minEA_set(swigCPtr, this, value);
  }

  public long getMinEA() {
    return IdaJavaJNI.idainfo_minEA_get(swigCPtr, this);
  }

  public void setMaxEA(long value) {
    IdaJavaJNI.idainfo_maxEA_set(swigCPtr, this, value);
  }

  public long getMaxEA() {
    return IdaJavaJNI.idainfo_maxEA_get(swigCPtr, this);
  }

  public void setOminEA(long value) {
    IdaJavaJNI.idainfo_ominEA_set(swigCPtr, this, value);
  }

  public long getOminEA() {
    return IdaJavaJNI.idainfo_ominEA_get(swigCPtr, this);
  }

  public void setOmaxEA(long value) {
    IdaJavaJNI.idainfo_omaxEA_set(swigCPtr, this, value);
  }

  public long getOmaxEA() {
    return IdaJavaJNI.idainfo_omaxEA_get(swigCPtr, this);
  }

  public void setLowoff(long value) {
    IdaJavaJNI.idainfo_lowoff_set(swigCPtr, this, value);
  }

  public long getLowoff() {
    return IdaJavaJNI.idainfo_lowoff_get(swigCPtr, this);
  }

  public void setHighoff(long value) {
    IdaJavaJNI.idainfo_highoff_set(swigCPtr, this, value);
  }

  public long getHighoff() {
    return IdaJavaJNI.idainfo_highoff_get(swigCPtr, this);
  }

  public void setMaxref(long value) {
    IdaJavaJNI.idainfo_maxref_set(swigCPtr, this, value);
  }

  public long getMaxref() {
    return IdaJavaJNI.idainfo_maxref_get(swigCPtr, this);
  }

  public void setASCIIbreak(short value) {
    IdaJavaJNI.idainfo_ASCIIbreak_set(swigCPtr, this, value);
  }

  public short getASCIIbreak() {
    return IdaJavaJNI.idainfo_ASCIIbreak_get(swigCPtr, this);
  }

  public void setWide_high_byte_first(short value) {
    IdaJavaJNI.idainfo_wide_high_byte_first_set(swigCPtr, this, value);
  }

  public short getWide_high_byte_first() {
    return IdaJavaJNI.idainfo_wide_high_byte_first_get(swigCPtr, this);
  }

  public void setIndent(short value) {
    IdaJavaJNI.idainfo_indent_set(swigCPtr, this, value);
  }

  public short getIndent() {
    return IdaJavaJNI.idainfo_indent_get(swigCPtr, this);
  }

  public void setComment(short value) {
    IdaJavaJNI.idainfo_comment_set(swigCPtr, this, value);
  }

  public short getComment() {
    return IdaJavaJNI.idainfo_comment_get(swigCPtr, this);
  }

  public void setXrefnum(short value) {
    IdaJavaJNI.idainfo_xrefnum_set(swigCPtr, this, value);
  }

  public short getXrefnum() {
    return IdaJavaJNI.idainfo_xrefnum_get(swigCPtr, this);
  }

  public void setS_entab(short value) {
    IdaJavaJNI.idainfo_s_entab_set(swigCPtr, this, value);
  }

  public short getS_entab() {
    return IdaJavaJNI.idainfo_s_entab_get(swigCPtr, this);
  }

  public void setSpecsegs(short value) {
    IdaJavaJNI.idainfo_specsegs_set(swigCPtr, this, value);
  }

  public short getSpecsegs() {
    return IdaJavaJNI.idainfo_specsegs_get(swigCPtr, this);
  }

  public void setS_void(short value) {
    IdaJavaJNI.idainfo_s_void_set(swigCPtr, this, value);
  }

  public short getS_void() {
    return IdaJavaJNI.idainfo_s_void_get(swigCPtr, this);
  }

  public void setS_reserved2(short value) {
    IdaJavaJNI.idainfo_s_reserved2_set(swigCPtr, this, value);
  }

  public short getS_reserved2() {
    return IdaJavaJNI.idainfo_s_reserved2_get(swigCPtr, this);
  }

  public void setS_showauto(short value) {
    IdaJavaJNI.idainfo_s_showauto_set(swigCPtr, this, value);
  }

  public short getS_showauto() {
    return IdaJavaJNI.idainfo_s_showauto_get(swigCPtr, this);
  }

  public void setS_auto(short value) {
    IdaJavaJNI.idainfo_s_auto_set(swigCPtr, this, value);
  }

  public short getS_auto() {
    return IdaJavaJNI.idainfo_s_auto_get(swigCPtr, this);
  }

  public void setS_limiter(short value) {
    IdaJavaJNI.idainfo_s_limiter_set(swigCPtr, this, value);
  }

  public short getS_limiter() {
    return IdaJavaJNI.idainfo_s_limiter_get(swigCPtr, this);
  }

  public void setS_null(short value) {
    IdaJavaJNI.idainfo_s_null_set(swigCPtr, this, value);
  }

  public short getS_null() {
    return IdaJavaJNI.idainfo_s_null_get(swigCPtr, this);
  }

  public void setS_genflags(short value) {
    IdaJavaJNI.idainfo_s_genflags_set(swigCPtr, this, value);
  }

  public short getS_genflags() {
    return IdaJavaJNI.idainfo_s_genflags_get(swigCPtr, this);
  }

  public boolean use_allasm() {
    return IdaJavaJNI.idainfo_use_allasm(swigCPtr, this);
  }

  public boolean loading_idc() {
    return IdaJavaJNI.idainfo_loading_idc(swigCPtr, this);
  }

  public void setS_showpref(short value) {
    IdaJavaJNI.idainfo_s_showpref_set(swigCPtr, this, value);
  }

  public short getS_showpref() {
    return IdaJavaJNI.idainfo_s_showpref_get(swigCPtr, this);
  }

  public void setS_prefseg(short value) {
    IdaJavaJNI.idainfo_s_prefseg_set(swigCPtr, this, value);
  }

  public short getS_prefseg() {
    return IdaJavaJNI.idainfo_s_prefseg_get(swigCPtr, this);
  }

  public void setAsmtype(short value) {
    IdaJavaJNI.idainfo_asmtype_set(swigCPtr, this, value);
  }

  public short getAsmtype() {
    return IdaJavaJNI.idainfo_asmtype_get(swigCPtr, this);
  }

  public void setBaseaddr(long value) {
    IdaJavaJNI.idainfo_baseaddr_set(swigCPtr, this, value);
  }

  public long getBaseaddr() {
    return IdaJavaJNI.idainfo_baseaddr_get(swigCPtr, this);
  }

  public void setS_xrefflag(short value) {
    IdaJavaJNI.idainfo_s_xrefflag_set(swigCPtr, this, value);
  }

  public short getS_xrefflag() {
    return IdaJavaJNI.idainfo_s_xrefflag_get(swigCPtr, this);
  }

  public void setBinSize(short value) {
    IdaJavaJNI.idainfo_binSize_set(swigCPtr, this, value);
  }

  public short getBinSize() {
    return IdaJavaJNI.idainfo_binSize_get(swigCPtr, this);
  }

  public void setS_cmtflg(short value) {
    IdaJavaJNI.idainfo_s_cmtflg_set(swigCPtr, this, value);
  }

  public short getS_cmtflg() {
    return IdaJavaJNI.idainfo_s_cmtflg_get(swigCPtr, this);
  }

  public void setNametype(char value) {
    IdaJavaJNI.idainfo_nametype_set(swigCPtr, this, value);
  }

  public char getNametype() {
    return IdaJavaJNI.idainfo_nametype_get(swigCPtr, this);
  }

  public void setS_showbads(short value) {
    IdaJavaJNI.idainfo_s_showbads_set(swigCPtr, this, value);
  }

  public short getS_showbads() {
    return IdaJavaJNI.idainfo_s_showbads_get(swigCPtr, this);
  }

  public void setS_prefflag(short value) {
    IdaJavaJNI.idainfo_s_prefflag_set(swigCPtr, this, value);
  }

  public short getS_prefflag() {
    return IdaJavaJNI.idainfo_s_prefflag_get(swigCPtr, this);
  }

  public void setS_packbase(short value) {
    IdaJavaJNI.idainfo_s_packbase_set(swigCPtr, this, value);
  }

  public short getS_packbase() {
    return IdaJavaJNI.idainfo_s_packbase_get(swigCPtr, this);
  }

  public void setAsciiflags(short value) {
    IdaJavaJNI.idainfo_asciiflags_set(swigCPtr, this, value);
  }

  public short getAsciiflags() {
    return IdaJavaJNI.idainfo_asciiflags_get(swigCPtr, this);
  }

  public void setListnames(short value) {
    IdaJavaJNI.idainfo_listnames_set(swigCPtr, this, value);
  }

  public short getListnames() {
    return IdaJavaJNI.idainfo_listnames_get(swigCPtr, this);
  }

  public void setASCIIpref(String value) {
    IdaJavaJNI.idainfo_ASCIIpref_set(swigCPtr, this, value);
  }

  public String getASCIIpref() {
    return IdaJavaJNI.idainfo_ASCIIpref_get(swigCPtr, this);
  }

  public void setASCIIsernum(long value) {
    IdaJavaJNI.idainfo_ASCIIsernum_set(swigCPtr, this, value);
  }

  public long getASCIIsernum() {
    return IdaJavaJNI.idainfo_ASCIIsernum_get(swigCPtr, this);
  }

  public void setASCIIzeroes(char value) {
    IdaJavaJNI.idainfo_ASCIIzeroes_set(swigCPtr, this, value);
  }

  public char getASCIIzeroes() {
    return IdaJavaJNI.idainfo_ASCIIzeroes_get(swigCPtr, this);
  }

  public void setGraph_view(short value) {
    IdaJavaJNI.idainfo_graph_view_set(swigCPtr, this, value);
  }

  public short getGraph_view() {
    return IdaJavaJNI.idainfo_graph_view_get(swigCPtr, this);
  }

  public void setS_reserved5(short value) {
    IdaJavaJNI.idainfo_s_reserved5_set(swigCPtr, this, value);
  }

  public short getS_reserved5() {
    return IdaJavaJNI.idainfo_s_reserved5_get(swigCPtr, this);
  }

  public void setTribyte_order(short value) {
    IdaJavaJNI.idainfo_tribyte_order_set(swigCPtr, this, value);
  }

  public short getTribyte_order() {
    return IdaJavaJNI.idainfo_tribyte_order_get(swigCPtr, this);
  }

  public void setMf(short value) {
    IdaJavaJNI.idainfo_mf_set(swigCPtr, this, value);
  }

  public short getMf() {
    return IdaJavaJNI.idainfo_mf_get(swigCPtr, this);
  }

  public void setS_org(short value) {
    IdaJavaJNI.idainfo_s_org_set(swigCPtr, this, value);
  }

  public short getS_org() {
    return IdaJavaJNI.idainfo_s_org_get(swigCPtr, this);
  }

  public void setS_assume(short value) {
    IdaJavaJNI.idainfo_s_assume_set(swigCPtr, this, value);
  }

  public short getS_assume() {
    return IdaJavaJNI.idainfo_s_assume_get(swigCPtr, this);
  }

  public void setS_checkarg(short value) {
    IdaJavaJNI.idainfo_s_checkarg_set(swigCPtr, this, value);
  }

  public short getS_checkarg() {
    return IdaJavaJNI.idainfo_s_checkarg_get(swigCPtr, this);
  }

  public void setStart_ss(long value) {
    IdaJavaJNI.idainfo_start_ss_set(swigCPtr, this, value);
  }

  public long getStart_ss() {
    return IdaJavaJNI.idainfo_start_ss_get(swigCPtr, this);
  }

  public void setStart_cs(long value) {
    IdaJavaJNI.idainfo_start_cs_set(swigCPtr, this, value);
  }

  public long getStart_cs() {
    return IdaJavaJNI.idainfo_start_cs_get(swigCPtr, this);
  }

  public void setMain(long value) {
    IdaJavaJNI.idainfo_main_set(swigCPtr, this, value);
  }

  public long getMain() {
    return IdaJavaJNI.idainfo_main_get(swigCPtr, this);
  }

  public void setShort_demnames(long value) {
    IdaJavaJNI.idainfo_short_demnames_set(swigCPtr, this, value);
  }

  public long getShort_demnames() {
    return IdaJavaJNI.idainfo_short_demnames_get(swigCPtr, this);
  }

  public void setLong_demnames(long value) {
    IdaJavaJNI.idainfo_long_demnames_set(swigCPtr, this, value);
  }

  public long getLong_demnames() {
    return IdaJavaJNI.idainfo_long_demnames_get(swigCPtr, this);
  }

  public void setDatatypes(long value) {
    IdaJavaJNI.idainfo_datatypes_set(swigCPtr, this, value);
  }

  public long getDatatypes() {
    return IdaJavaJNI.idainfo_datatypes_get(swigCPtr, this);
  }

  public void setStrtype(int value) {
    IdaJavaJNI.idainfo_strtype_set(swigCPtr, this, value);
  }

  public int getStrtype() {
    return IdaJavaJNI.idainfo_strtype_get(swigCPtr, this);
  }

  public void setAf2(int value) {
    IdaJavaJNI.idainfo_af2_set(swigCPtr, this, value);
  }

  public int getAf2() {
    return IdaJavaJNI.idainfo_af2_get(swigCPtr, this);
  }

  public void setNamelen(int value) {
    IdaJavaJNI.idainfo_namelen_set(swigCPtr, this, value);
  }

  public int getNamelen() {
    return IdaJavaJNI.idainfo_namelen_get(swigCPtr, this);
  }

  public void setMargin(int value) {
    IdaJavaJNI.idainfo_margin_set(swigCPtr, this, value);
  }

  public int getMargin() {
    return IdaJavaJNI.idainfo_margin_get(swigCPtr, this);
  }

  public void setLenxref(int value) {
    IdaJavaJNI.idainfo_lenxref_set(swigCPtr, this, value);
  }

  public int getLenxref() {
    return IdaJavaJNI.idainfo_lenxref_get(swigCPtr, this);
  }

  public void setLprefix(String value) {
    IdaJavaJNI.idainfo_lprefix_set(swigCPtr, this, value);
  }

  public String getLprefix() {
    return IdaJavaJNI.idainfo_lprefix_get(swigCPtr, this);
  }

  public void setLprefixlen(short value) {
    IdaJavaJNI.idainfo_lprefixlen_set(swigCPtr, this, value);
  }

  public short getLprefixlen() {
    return IdaJavaJNI.idainfo_lprefixlen_get(swigCPtr, this);
  }

  public void setCc(compiler_info_t value) {
    IdaJavaJNI.idainfo_cc_set(swigCPtr, this, compiler_info_t.getCPtr(value), value);
  }

  public compiler_info_t getCc() {
    long cPtr = IdaJavaJNI.idainfo_cc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new compiler_info_t(cPtr, false);
  }

  public void setDatabase_change_count(long value) {
    IdaJavaJNI.idainfo_database_change_count_set(swigCPtr, this, value);
  }

  public long getDatabase_change_count() {
    return IdaJavaJNI.idainfo_database_change_count_get(swigCPtr, this);
  }

  public void setSize_ldbl(short value) {
    IdaJavaJNI.idainfo_size_ldbl_set(swigCPtr, this, value);
  }

  public short getSize_ldbl() {
    return IdaJavaJNI.idainfo_size_ldbl_get(swigCPtr, this);
  }

  public void setAppcall_options(long value) {
    IdaJavaJNI.idainfo_appcall_options_set(swigCPtr, this, value);
  }

  public long getAppcall_options() {
    return IdaJavaJNI.idainfo_appcall_options_get(swigCPtr, this);
  }

  public void setReserved(short[] value) {
    IdaJavaJNI.idainfo_reserved_set(swigCPtr, this, value);
  }

  public short[] getReserved() {
    return IdaJavaJNI.idainfo_reserved_get(swigCPtr, this);
  }

  public idainfo() {
    this(IdaJavaJNI.new_idainfo(), true);
  }

}
