/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class IdaJava implements IdaJavaConstants {
  public static boolean can_place32(SWIGTYPE_p_ulonglong a) {
    return IdaJavaJNI.can_place32__SWIG_0(SWIGTYPE_p_ulonglong.getCPtr(a));
  }

  public static boolean can_place32(SWIGTYPE_p_longlong a) {
    return IdaJavaJNI.can_place32__SWIG_1(SWIGTYPE_p_longlong.getCPtr(a));
  }

  public static void qexit(int code) {
    IdaJavaJNI.qexit(code);
  }

  public static boolean test_bit(SWIGTYPE_p_unsigned_char bitmap, long bit) {
    return IdaJavaJNI.test_bit(SWIGTYPE_p_unsigned_char.getCPtr(bitmap), bit);
  }

  public static void set_bit(SWIGTYPE_p_unsigned_char bitmap, long bit) {
    IdaJavaJNI.set_bit(SWIGTYPE_p_unsigned_char.getCPtr(bitmap), bit);
  }

  public static void clear_bit(SWIGTYPE_p_unsigned_char bitmap, long bit) {
    IdaJavaJNI.clear_bit(SWIGTYPE_p_unsigned_char.getCPtr(bitmap), bit);
  }

  public static void set_all_bits(SWIGTYPE_p_unsigned_char bitmap, long nbits) {
    IdaJavaJNI.set_all_bits(SWIGTYPE_p_unsigned_char.getCPtr(bitmap), nbits);
  }

  public static void clear_all_bits(SWIGTYPE_p_unsigned_char bitmap, long nbits) {
    IdaJavaJNI.clear_all_bits(SWIGTYPE_p_unsigned_char.getCPtr(bitmap), nbits);
  }

  public static boolean overlap(long off1, long s1, long off2, long s2) {
    return IdaJavaJNI.overlap(off1, s1, off2, s2);
  }

  public static boolean includes(long off1, long s1, long off2, long s2) {
    return IdaJavaJNI.includes(off1, s1, off2, s2);
  }

  public static boolean contains(long off1, long s1, long off) {
    return IdaJavaJNI.contains(off1, s1, off);
  }

  public static int readbytes(int h, SWIGTYPE_p_unsigned_int res, int size, boolean mf) {
    return IdaJavaJNI.readbytes(h, SWIGTYPE_p_unsigned_int.getCPtr(res), size, mf);
  }

  public static int writebytes(int h, long l, int size, boolean mf) {
    return IdaJavaJNI.writebytes(h, l, size, mf);
  }

  public static int read2bytes(int h, SWIGTYPE_p_unsigned_short res, boolean mf) {
    return IdaJavaJNI.read2bytes(h, SWIGTYPE_p_unsigned_short.getCPtr(res), mf);
  }

  public static long swap32(long x) {
    return IdaJavaJNI.swap32(x);
  }

  public static int swap16(int x) {
    return IdaJavaJNI.swap16(x);
  }

  public static void swap_value(SWIGTYPE_p_void dst, SWIGTYPE_p_void src, int size) {
    IdaJavaJNI.swap_value(SWIGTYPE_p_void.getCPtr(dst), SWIGTYPE_p_void.getCPtr(src), size);
  }

  public static void reloc_value(SWIGTYPE_p_void value, int size, int delta, boolean mf) {
    IdaJavaJNI.reloc_value(SWIGTYPE_p_void.getCPtr(value), size, delta, mf);
  }

  public static long rotate_left(long x, int count, long bits, long offset) {
    return IdaJavaJNI.rotate_left(x, count, bits, offset);
  }

  public static SWIGTYPE_p_void qalloc_or_throw(long size) {
    long cPtr = IdaJavaJNI.qalloc_or_throw(size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_void qrealloc_or_throw(SWIGTYPE_p_void ptr, long size) {
    long cPtr = IdaJavaJNI.qrealloc_or_throw(SWIGTYPE_p_void.getCPtr(ptr), size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static long qstrlen(String s) {
    return IdaJavaJNI.qstrlen__SWIG_0(s);
  }

  public static long qstrlen(SWIGTYPE_p_unsigned_char s) {
    return IdaJavaJNI.qstrlen__SWIG_1(SWIGTYPE_p_unsigned_char.getCPtr(s));
  }

  public static long qstrlen(SWIGTYPE_p_wchar16_t s) {
    return IdaJavaJNI.qstrlen__SWIG_2(SWIGTYPE_p_wchar16_t.getCPtr(s));
  }

  public static int qstrcmp(String s1, String s2) {
    return IdaJavaJNI.qstrcmp__SWIG_0(s1, s2);
  }

  public static int qstrcmp(SWIGTYPE_p_unsigned_char s1, SWIGTYPE_p_unsigned_char s2) {
    return IdaJavaJNI.qstrcmp__SWIG_1(SWIGTYPE_p_unsigned_char.getCPtr(s1), SWIGTYPE_p_unsigned_char.getCPtr(s2));
  }

  public static int qstrcmp(SWIGTYPE_p_wchar16_t s1, SWIGTYPE_p_wchar16_t s2) {
    return IdaJavaJNI.qstrcmp__SWIG_2(SWIGTYPE_p_wchar16_t.getCPtr(s1), SWIGTYPE_p_wchar16_t.getCPtr(s2));
  }

  public static String qstrstr(String s1, String s2) {
    return IdaJavaJNI.qstrstr__SWIG_0(s1, s2);
  }

  public static SWIGTYPE_p_unsigned_char qstrstr(SWIGTYPE_p_unsigned_char s1, SWIGTYPE_p_unsigned_char s2) {
    long cPtr = IdaJavaJNI.qstrstr__SWIG_1(SWIGTYPE_p_unsigned_char.getCPtr(s1), SWIGTYPE_p_unsigned_char.getCPtr(s2));
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static String qstrchr(String s1, char c) {
    return IdaJavaJNI.qstrchr__SWIG_0(s1, c);
  }

  public static SWIGTYPE_p_unsigned_char qstrchr(SWIGTYPE_p_unsigned_char s1, short c) {
    long cPtr = IdaJavaJNI.qstrchr__SWIG_1(SWIGTYPE_p_unsigned_char.getCPtr(s1), c);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static SWIGTYPE_p_wchar16_t qstrchr(SWIGTYPE_p_wchar16_t s1, SWIGTYPE_p_wchar16_t c) {
    long cPtr = IdaJavaJNI.qstrchr__SWIG_2(SWIGTYPE_p_wchar16_t.getCPtr(s1), SWIGTYPE_p_wchar16_t.getCPtr(c));
    return (cPtr == 0) ? null : new SWIGTYPE_p_wchar16_t(cPtr, false);
  }

  public static String qstrrchr(String s1, char c) {
    return IdaJavaJNI.qstrrchr__SWIG_0(s1, c);
  }

  public static SWIGTYPE_p_unsigned_char qstrrchr(SWIGTYPE_p_unsigned_char s1, short c) {
    long cPtr = IdaJavaJNI.qstrrchr__SWIG_1(SWIGTYPE_p_unsigned_char.getCPtr(s1), c);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public static SWIGTYPE_p_wchar16_t qstrrchr(SWIGTYPE_p_wchar16_t s1, SWIGTYPE_p_wchar16_t c) {
    long cPtr = IdaJavaJNI.qstrrchr__SWIG_2(SWIGTYPE_p_wchar16_t.getCPtr(s1), SWIGTYPE_p_wchar16_t.getCPtr(c));
    return (cPtr == 0) ? null : new SWIGTYPE_p_wchar16_t(cPtr, false);
  }

  public static boolean relocate_relobj(relobj_t _relobj, long ea, boolean mf) {
    return IdaJavaJNI.relocate_relobj(relobj_t.getCPtr(_relobj), _relobj, ea, mf);
  }

  public static long parse_command_line(String cmdline, SWIGTYPE_p_qvectorT__qstringT_char_t_t args) {
    return IdaJavaJNI.parse_command_line(cmdline, SWIGTYPE_p_qvectorT__qstringT_char_t_t.getCPtr(args));
  }

  public static boolean u2cstr(SWIGTYPE_p_wchar16_t in, SWIGTYPE_p__qstringT_char_t out, int nsyms) {
    return IdaJavaJNI.u2cstr__SWIG_0(SWIGTYPE_p_wchar16_t.getCPtr(in), SWIGTYPE_p__qstringT_char_t.getCPtr(out), nsyms);
  }

  public static boolean u2cstr(SWIGTYPE_p_wchar16_t in, SWIGTYPE_p__qstringT_char_t out) {
    return IdaJavaJNI.u2cstr__SWIG_1(SWIGTYPE_p_wchar16_t.getCPtr(in), SWIGTYPE_p__qstringT_char_t.getCPtr(out));
  }

  public static boolean c2ustr(String in, SWIGTYPE_p__qstringT_wchar16_t_t out, int nsyms) {
    return IdaJavaJNI.c2ustr__SWIG_0(in, SWIGTYPE_p__qstringT_wchar16_t_t.getCPtr(out), nsyms);
  }

  public static boolean c2ustr(String in, SWIGTYPE_p__qstringT_wchar16_t_t out) {
    return IdaJavaJNI.c2ustr__SWIG_1(in, SWIGTYPE_p__qstringT_wchar16_t_t.getCPtr(out));
  }

  public static int utf8_unicode(String in, SWIGTYPE_p_wchar16_t out, long outsize) {
    return IdaJavaJNI.utf8_unicode(in, SWIGTYPE_p_wchar16_t.getCPtr(out), outsize);
  }

  public static boolean win_utf2idb(String buf) {
    return IdaJavaJNI.win_utf2idb(buf);
  }

  public static void char2oem(String arg0) {
    IdaJavaJNI.char2oem(arg0);
  }

  public static void oem2char(String arg0) {
    IdaJavaJNI.oem2char(arg0);
  }

  public static boolean set_codepages(int arg0, int arg1) {
    return IdaJavaJNI.set_codepages(arg0, arg1);
  }

  public static int get_codepages(SWIGTYPE_p_int arg0) {
    return IdaJavaJNI.get_codepages(SWIGTYPE_p_int.getCPtr(arg0));
  }

  public static int convert_codepage(String in, int insize, String out, long outsize, int incp, int outcp, int flags) {
    return IdaJavaJNI.convert_codepage__SWIG_0(in, insize, out, outsize, incp, outcp, flags);
  }

  public static int convert_codepage(String in, int insize, String out, long outsize, int incp, int outcp) {
    return IdaJavaJNI.convert_codepage__SWIG_1(in, insize, out, outsize, incp, outcp);
  }

  public static void setSubstChar(char value) {
    IdaJavaJNI.SubstChar_set(value);
  }

  public static char getSubstChar() {
    return IdaJavaJNI.SubstChar_get();
  }

  public static SWIGTYPE_p_void init_process(launch_process_t lpi, SWIGTYPE_p__qstringT_char_t errbuf) {
    long cPtr = IdaJavaJNI.init_process(launch_process_t.getCPtr(lpi), lpi, SWIGTYPE_p__qstringT_char_t.getCPtr(errbuf));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static int term_process(SWIGTYPE_p_void handle) {
    return IdaJavaJNI.term_process(SWIGTYPE_p_void.getCPtr(handle));
  }

  public static int get_process_exit_code(SWIGTYPE_p_void handle, SWIGTYPE_p_int exit_code) {
    return IdaJavaJNI.get_process_exit_code(SWIGTYPE_p_void.getCPtr(handle), SWIGTYPE_p_int.getCPtr(exit_code));
  }

  public static __qthread_t qthread_create(SWIGTYPE_p_f_p_void__int thread_cb, SWIGTYPE_p_void ud) {
    long cPtr = IdaJavaJNI.qthread_create(SWIGTYPE_p_f_p_void__int.getCPtr(thread_cb), SWIGTYPE_p_void.getCPtr(ud));
    return (cPtr == 0) ? null : new __qthread_t(cPtr, false);
  }

  public static void qthread_free(__qthread_t q) {
    IdaJavaJNI.qthread_free(__qthread_t.getCPtr(q), q);
  }

  public static boolean qthread_join(__qthread_t q) {
    return IdaJavaJNI.qthread_join(__qthread_t.getCPtr(q), q);
  }

  public static boolean qthread_kill(__qthread_t q) {
    return IdaJavaJNI.qthread_kill(__qthread_t.getCPtr(q), q);
  }

  public static __qthread_t qthread_self() {
    long cPtr = IdaJavaJNI.qthread_self();
    return (cPtr == 0) ? null : new __qthread_t(cPtr, false);
  }

  public static __qsemaphore_t qsem_create(String name, int init_count) {
    long cPtr = IdaJavaJNI.qsem_create(name, init_count);
    return (cPtr == 0) ? null : new __qsemaphore_t(cPtr, false);
  }

  public static boolean qsem_free(__qsemaphore_t sem) {
    return IdaJavaJNI.qsem_free(__qsemaphore_t.getCPtr(sem), sem);
  }

  public static boolean qsem_post(__qsemaphore_t sem) {
    return IdaJavaJNI.qsem_post(__qsemaphore_t.getCPtr(sem), sem);
  }

  public static boolean qsem_wait(__qsemaphore_t sem, int timeout_ms) {
    return IdaJavaJNI.qsem_wait(__qsemaphore_t.getCPtr(sem), sem, timeout_ms);
  }

  public static boolean qmutex_free(__qmutex_t m) {
    return IdaJavaJNI.qmutex_free(__qmutex_t.getCPtr(m), m);
  }

  public static __qmutex_t qmutex_create() {
    long cPtr = IdaJavaJNI.qmutex_create();
    return (cPtr == 0) ? null : new __qmutex_t(cPtr, false);
  }

  public static boolean qmutex_lock(__qmutex_t m) {
    return IdaJavaJNI.qmutex_lock(__qmutex_t.getCPtr(m), m);
  }

  public static boolean qmutex_unlock(__qmutex_t m) {
    return IdaJavaJNI.qmutex_unlock(__qmutex_t.getCPtr(m), m);
  }

  public static String print(long l, long h, String buf, int bufsize, int radix, int issigned) {
    return IdaJavaJNI.print__SWIG_0(l, h, buf, bufsize, radix, issigned);
  }

  public static SWIGTYPE_p_longlong make_longlong(long ll, int hh) {
    return new SWIGTYPE_p_longlong(IdaJavaJNI.make_longlong(ll, hh), true);
  }

  public static SWIGTYPE_p_ulonglong make_ulonglong(long ll, int hh) {
    return new SWIGTYPE_p_ulonglong(IdaJavaJNI.make_ulonglong(ll, hh), true);
  }

  public static long low(SWIGTYPE_p_ulonglong x) {
    return IdaJavaJNI.low__SWIG_0(SWIGTYPE_p_ulonglong.getCPtr(x));
  }

  public static long high(SWIGTYPE_p_ulonglong x) {
    return IdaJavaJNI.high__SWIG_0(SWIGTYPE_p_ulonglong.getCPtr(x));
  }

  public static long low(SWIGTYPE_p_longlong x) {
    return IdaJavaJNI.low__SWIG_1(SWIGTYPE_p_longlong.getCPtr(x));
  }

  public static int high(SWIGTYPE_p_longlong x) {
    return IdaJavaJNI.high__SWIG_1(SWIGTYPE_p_longlong.getCPtr(x));
  }

  public static String print(SWIGTYPE_p_longlong x, String buf, int bufsize, int radix) {
    return IdaJavaJNI.print__SWIG_1(SWIGTYPE_p_longlong.getCPtr(x), buf, bufsize, radix);
  }

  public static String print(SWIGTYPE_p_ulonglong x, String buf, int bufsize, int radix) {
    return IdaJavaJNI.print__SWIG_2(SWIGTYPE_p_ulonglong.getCPtr(x), buf, bufsize, radix);
  }

  public static SWIGTYPE_p_longlong llong_scan(String buf, int radix, SWIGTYPE_p_p_char end) {
    return new SWIGTYPE_p_longlong(IdaJavaJNI.llong_scan(buf, radix, SWIGTYPE_p_p_char.getCPtr(end)), true);
  }

  public static SWIGTYPE_p_ulonglong swap64(SWIGTYPE_p_ulonglong arg0) {
    return new SWIGTYPE_p_ulonglong(IdaJavaJNI.swap64__SWIG_0(SWIGTYPE_p_ulonglong.getCPtr(arg0)), true);
  }

  public static SWIGTYPE_p_longlong swap64(SWIGTYPE_p_longlong x) {
    return new SWIGTYPE_p_longlong(IdaJavaJNI.swap64__SWIG_1(SWIGTYPE_p_longlong.getCPtr(x)), true);
  }

  public static void swap128(SWIGTYPE_p_uint128 x) {
    IdaJavaJNI.swap128(SWIGTYPE_p_uint128.getCPtr(x));
  }

  public static void setInf(idainfo value) {
    IdaJavaJNI.inf_set(idainfo.getCPtr(value), value);
  }

  public static idainfo getInf() {
    long cPtr = IdaJavaJNI.inf_get();
    return (cPtr == 0) ? null : new idainfo(cPtr, false);
  }

  public static void setDto(text_options_t value) {
    IdaJavaJNI.dto_set(text_options_t.getCPtr(value), value);
  }

  public static text_options_t getDto() {
    long cPtr = IdaJavaJNI.dto_get();
    return (cPtr == 0) ? null : new text_options_t(cPtr, false);
  }

  public static boolean showRepeatables() {
    return IdaJavaJNI.showRepeatables();
  }

  public static boolean showAllComments() {
    return IdaJavaJNI.showAllComments();
  }

  public static boolean showComments() {
    return IdaJavaJNI.showComments();
  }

  public static boolean should_trace_sp() {
    return IdaJavaJNI.should_trace_sp();
  }

  public static boolean should_create_stkvars() {
    return IdaJavaJNI.should_create_stkvars();
  }

  public static int calc_default_idaplace_flags() {
    return IdaJavaJNI.calc_default_idaplace_flags();
  }

  public static long toEA(long reg_cs, long reg_ip) {
    return IdaJavaJNI.toEA(reg_cs, reg_ip);
  }

  public static String idb2scr(String name) {
    return IdaJavaJNI.idb2scr(name);
  }

  public static String scr2idb(String name) {
    return IdaJavaJNI.scr2idb(name);
  }

  public static String ansi2idb(String name) {
    return IdaJavaJNI.ansi2idb(name);
  }

  public static void dto_copy_to_inf(dual_text_options_t arg0, idainfo inf) {
    IdaJavaJNI.dto_copy_to_inf(dual_text_options_t.getCPtr(arg0), arg0, idainfo.getCPtr(inf), inf);
  }

  public static void dto_copy_from_inf(dual_text_options_t arg0, idainfo inf) {
    IdaJavaJNI.dto_copy_from_inf(dual_text_options_t.getCPtr(arg0), arg0, idainfo.getCPtr(inf), inf);
  }

  public static void dto_init(dual_text_options_t dt, boolean for_graph) {
    IdaJavaJNI.dto_init(dual_text_options_t.getCPtr(dt), dt, for_graph);
  }

  public static SWIGTYPE_p_FILE qfopen(String file, String mode) {
    long cPtr = IdaJavaJNI.qfopen(file, mode);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static int qfread(SWIGTYPE_p_FILE fp, SWIGTYPE_p_void buf, long n) {
    return IdaJavaJNI.qfread(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_void.getCPtr(buf), n);
  }

  public static int qfwrite(SWIGTYPE_p_FILE fp, SWIGTYPE_p_void buf, long n) {
    return IdaJavaJNI.qfwrite(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_void.getCPtr(buf), n);
  }

  public static int qftell(SWIGTYPE_p_FILE fp) {
    return IdaJavaJNI.qftell(SWIGTYPE_p_FILE.getCPtr(fp));
  }

  public static int qfseek(SWIGTYPE_p_FILE fp, int offset, int whence) {
    return IdaJavaJNI.qfseek(SWIGTYPE_p_FILE.getCPtr(fp), offset, whence);
  }

  public static int qfclose(SWIGTYPE_p_FILE fp) {
    return IdaJavaJNI.qfclose(SWIGTYPE_p_FILE.getCPtr(fp));
  }

  public static int qflush(SWIGTYPE_p_FILE fp) {
    return IdaJavaJNI.qflush(SWIGTYPE_p_FILE.getCPtr(fp));
  }

  public static SWIGTYPE_p_FILE qtmpfile() {
    long cPtr = IdaJavaJNI.qtmpfile();
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static int qrename(String oldfname, String newfname) {
    return IdaJavaJNI.qrename(oldfname, newfname);
  }

  public static String qtmpnam(String buf, long bufsize) {
    return IdaJavaJNI.qtmpnam(buf, bufsize);
  }

  public static int qfputc(int chr, SWIGTYPE_p_FILE fp) {
    return IdaJavaJNI.qfputc(chr, SWIGTYPE_p_FILE.getCPtr(fp));
  }

  public static int qfgetc(SWIGTYPE_p_FILE fp) {
    return IdaJavaJNI.qfgetc(SWIGTYPE_p_FILE.getCPtr(fp));
  }

  public static String qfgets(String s, long len, SWIGTYPE_p_FILE fp) {
    return IdaJavaJNI.qfgets(s, len, SWIGTYPE_p_FILE.getCPtr(fp));
  }

  public static int qfputs(String s, SWIGTYPE_p_FILE fp) {
    return IdaJavaJNI.qfputs(s, SWIGTYPE_p_FILE.getCPtr(fp));
  }

  public static int qvfprintf(SWIGTYPE_p_FILE fp, String format, SWIGTYPE_p_va_list va) {
    return IdaJavaJNI.qvfprintf(SWIGTYPE_p_FILE.getCPtr(fp), format, SWIGTYPE_p_va_list.getCPtr(va));
  }

  public static int qvprintf(String format, SWIGTYPE_p_va_list va) {
    return IdaJavaJNI.qvprintf(format, SWIGTYPE_p_va_list.getCPtr(va));
  }

  public static int qvfscanf(SWIGTYPE_p_FILE fp, String format, SWIGTYPE_p_va_list va) {
    return IdaJavaJNI.qvfscanf(SWIGTYPE_p_FILE.getCPtr(fp), format, SWIGTYPE_p_va_list.getCPtr(va));
  }

  public static String qgets(String line, long linesize) {
    return IdaJavaJNI.qgets(line, linesize);
  }

  public static int qfprintf(SWIGTYPE_p_FILE fp, String format) {
    return IdaJavaJNI.qfprintf(SWIGTYPE_p_FILE.getCPtr(fp), format);
  }

  public static int qprintf(String format) {
    return IdaJavaJNI.qprintf(format);
  }

  public static int freadbytes(SWIGTYPE_p_FILE fp, SWIGTYPE_p_void res, int size, int mostfirst) {
    return IdaJavaJNI.freadbytes(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_void.getCPtr(res), size, mostfirst);
  }

  public static int fwritebytes(SWIGTYPE_p_FILE fp, SWIGTYPE_p_void l, int size, int mostfirst) {
    return IdaJavaJNI.fwritebytes(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_void.getCPtr(l), size, mostfirst);
  }

  public static int fread2bytes(SWIGTYPE_p_FILE fp, SWIGTYPE_p_short res, boolean mostfirst) {
    return IdaJavaJNI.fread2bytes__SWIG_0(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_short.getCPtr(res), mostfirst);
  }

  public static int fwrite2bytes(SWIGTYPE_p_FILE fp, SWIGTYPE_p_short res, boolean mostfirst) {
    return IdaJavaJNI.fwrite2bytes__SWIG_0(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_short.getCPtr(res), mostfirst);
  }

  public static int fread2bytes(SWIGTYPE_p_FILE fp, SWIGTYPE_p_unsigned_short res, boolean mostfirst) {
    return IdaJavaJNI.fread2bytes__SWIG_1(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_unsigned_short.getCPtr(res), mostfirst);
  }

  public static int fwrite2bytes(SWIGTYPE_p_FILE fp, SWIGTYPE_p_unsigned_short res, boolean mostfirst) {
    return IdaJavaJNI.fwrite2bytes__SWIG_1(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_unsigned_short.getCPtr(res), mostfirst);
  }

  public static int fread4bytes(SWIGTYPE_p_FILE fp, SWIGTYPE_p_int res, boolean mostfirst) {
    return IdaJavaJNI.fread4bytes__SWIG_0(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_int.getCPtr(res), mostfirst);
  }

  public static int fwrite4bytes(SWIGTYPE_p_FILE fp, SWIGTYPE_p_int res, boolean mostfirst) {
    return IdaJavaJNI.fwrite4bytes__SWIG_0(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_int.getCPtr(res), mostfirst);
  }

  public static int fread4bytes(SWIGTYPE_p_FILE fp, SWIGTYPE_p_unsigned_int res, boolean mostfirst) {
    return IdaJavaJNI.fread4bytes__SWIG_1(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_unsigned_int.getCPtr(res), mostfirst);
  }

  public static int fwrite4bytes(SWIGTYPE_p_FILE fp, SWIGTYPE_p_unsigned_int res, boolean mostfirst) {
    return IdaJavaJNI.fwrite4bytes__SWIG_1(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_unsigned_int.getCPtr(res), mostfirst);
  }

  public static int fread8bytes(SWIGTYPE_p_FILE fp, SWIGTYPE_p_longlong res, boolean mostfirst) {
    return IdaJavaJNI.fread8bytes__SWIG_0(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_longlong.getCPtr(res), mostfirst);
  }

  public static int fwrite8bytes(SWIGTYPE_p_FILE fp, SWIGTYPE_p_longlong res, boolean mostfirst) {
    return IdaJavaJNI.fwrite8bytes__SWIG_0(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_longlong.getCPtr(res), mostfirst);
  }

  public static int fread8bytes(SWIGTYPE_p_FILE fp, SWIGTYPE_p_ulonglong res, boolean mostfirst) {
    return IdaJavaJNI.fread8bytes__SWIG_1(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_ulonglong.getCPtr(res), mostfirst);
  }

  public static int fwrite8bytes(SWIGTYPE_p_FILE fp, SWIGTYPE_p_ulonglong res, boolean mostfirst) {
    return IdaJavaJNI.fwrite8bytes__SWIG_1(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_ulonglong.getCPtr(res), mostfirst);
  }

  public static String ivalue(int mes, String buf, long bufsize) {
    return IdaJavaJNI.ivalue(mes, buf, bufsize);
  }

  public static String qivalue(int mes) {
    return IdaJavaJNI.qivalue(mes);
  }

  public static int get_predef_insn_cmt(SWIGTYPE_p_insn_t cmd, String buf, long bufsize) {
    return IdaJavaJNI.get_predef_insn_cmt(SWIGTYPE_p_insn_t.getCPtr(cmd), buf, bufsize);
  }

  public static int get_predef_cmt(String info, int wrktyp, String buf, long bufsize) {
    return IdaJavaJNI.get_predef_cmt(info, wrktyp, buf, bufsize);
  }

  public static int askaddr(long[] OUTPUT, String format) {
    return IdaJavaJNI.askaddr(OUTPUT, format);
  }

  public static void setDirty_infos(int value) {
    IdaJavaJNI.dirty_infos_set(value);
  }

  public static int getDirty_infos() {
    return IdaJavaJNI.dirty_infos_get();
  }

  public static void request_refresh(int mask) {
    IdaJavaJNI.request_refresh(mask);
  }

  public static boolean jumpto(long ea, int opnum) {
    return IdaJavaJNI.jumpto__SWIG_0(ea, opnum);
  }

  public static boolean jumpto(long ea) {
    return IdaJavaJNI.jumpto__SWIG_1(ea);
  }

  public static boolean banner(int wait) {
    return IdaJavaJNI.banner(wait);
  }

  public static boolean is_msg_inited() {
    return IdaJavaJNI.is_msg_inited();
  }

  public static void refresh_idaview() {
    IdaJavaJNI.refresh_idaview();
  }

  public static void refresh_idaview_anyway() {
    IdaJavaJNI.refresh_idaview_anyway();
  }

  public static void analyzer_options() {
    IdaJavaJNI.analyzer_options();
  }

  public static long get_screen_ea() {
    return IdaJavaJNI.get_screen_ea();
  }

  public static int get_opnum() {
    return IdaJavaJNI.get_opnum();
  }

  public static boolean get_cursor(int[] x, int[] y) {
    return IdaJavaJNI.get_cursor(x, y);
  }

  public static String get_curline() {
    return IdaJavaJNI.get_curline();
  }

  public static boolean read_selection(long[] ea1, long[] ea2) {
    return IdaJavaJNI.read_selection(ea1, ea2);
  }

  public static void unmark_selection() {
    IdaJavaJNI.unmark_selection();
  }

  public static void open_url(String url) {
    IdaJavaJNI.open_url(url);
  }

  public static long get_hexdump_ea(int hexdump_num) {
    return IdaJavaJNI.get_hexdump_ea(hexdump_num);
  }

  public static boolean set_xml(String path, String name, String value) {
    return IdaJavaJNI.set_xml__SWIG_0(path, name, value);
  }

  public static boolean get_xml(String path, SWIGTYPE_p_idc_value_t value) {
    return IdaJavaJNI.get_xml(path, SWIGTYPE_p_idc_value_t.getCPtr(value));
  }

  public static boolean del_xml(String path) {
    return IdaJavaJNI.del_xml(path);
  }

  public static boolean push_xml(String path) {
    return IdaJavaJNI.push_xml(path);
  }

  public static boolean pop_xml() {
    return IdaJavaJNI.pop_xml();
  }

  public static int get_key_code(String keyname) {
    return IdaJavaJNI.get_key_code(keyname);
  }

  public static void refresh_navband(boolean force) {
    IdaJavaJNI.refresh_navband(force);
  }

  public static boolean refresh_chooser(String title) {
    return IdaJavaJNI.refresh_chooser(title);
  }

  public static boolean close_chooser(String title) {
    return IdaJavaJNI.close_chooser(title);
  }

  public static void install_command_interpreter(SWIGTYPE_p_cli_t cp) {
    IdaJavaJNI.install_command_interpreter(SWIGTYPE_p_cli_t.getCPtr(cp));
  }

  public static void remove_command_interpreter(SWIGTYPE_p_cli_t cp) {
    IdaJavaJNI.remove_command_interpreter(SWIGTYPE_p_cli_t.getCPtr(cp));
  }

  public static void gen_disasm_text(long ea1, long ea2, SWIGTYPE_p_text_t text, boolean truncate_lines) {
    IdaJavaJNI.gen_disasm_text(ea1, ea2, SWIGTYPE_p_text_t.getCPtr(text), truncate_lines);
  }

  public static int execute_sync(exec_request_t req, int reqf) {
    return IdaJavaJNI.execute_sync(exec_request_t.getCPtr(req), req, reqf);
  }

  public static boolean set_dock_pos(String src_ctrl, String dest_ctrl, int orient, int left, int top, int right, int bottom) {
    return IdaJavaJNI.set_dock_pos__SWIG_0(src_ctrl, dest_ctrl, orient, left, top, right, bottom);
  }

  public static boolean set_dock_pos(String src_ctrl, String dest_ctrl, int orient, int left, int top, int right) {
    return IdaJavaJNI.set_dock_pos__SWIG_1(src_ctrl, dest_ctrl, orient, left, top, right);
  }

  public static boolean set_dock_pos(String src_ctrl, String dest_ctrl, int orient, int left, int top) {
    return IdaJavaJNI.set_dock_pos__SWIG_2(src_ctrl, dest_ctrl, orient, left, top);
  }

  public static boolean set_dock_pos(String src_ctrl, String dest_ctrl, int orient, int left) {
    return IdaJavaJNI.set_dock_pos__SWIG_3(src_ctrl, dest_ctrl, orient, left);
  }

  public static boolean set_dock_pos(String src_ctrl, String dest_ctrl, int orient) {
    return IdaJavaJNI.set_dock_pos__SWIG_4(src_ctrl, dest_ctrl, orient);
  }

  public static boolean enable_input_hotkeys(boolean enable) {
    return IdaJavaJNI.enable_input_hotkeys(enable);
  }

  public static boolean add_menu_item(String menupath, String name, String hotkey, int flags, SWIGTYPE_p_f_p_void__bool callback, SWIGTYPE_p_void ud) {
    return IdaJavaJNI.add_menu_item(menupath, name, hotkey, flags, SWIGTYPE_p_f_p_void__bool.getCPtr(callback), SWIGTYPE_p_void.getCPtr(ud));
  }

  public static boolean del_menu_item(String menupath) {
    return IdaJavaJNI.del_menu_item(menupath);
  }

  public static SWIGTYPE_p_Forms__TForm create_tform(String caption, SWIGTYPE_p_int handle) {
    long cPtr = IdaJavaJNI.create_tform(caption, SWIGTYPE_p_int.getCPtr(handle));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static int get_tform_handle(SWIGTYPE_p_Forms__TForm form) {
    return IdaJavaJNI.get_tform_handle(SWIGTYPE_p_Forms__TForm.getCPtr(form));
  }

  public static void open_tform(SWIGTYPE_p_Forms__TForm form, int options) {
    IdaJavaJNI.open_tform(SWIGTYPE_p_Forms__TForm.getCPtr(form), options);
  }

  public static void close_tform(SWIGTYPE_p_Forms__TForm form, int options) {
    IdaJavaJNI.close_tform(SWIGTYPE_p_Forms__TForm.getCPtr(form), options);
  }

  public static void switchto_tform(SWIGTYPE_p_Forms__TForm form, boolean take_focus) {
    IdaJavaJNI.switchto_tform(SWIGTYPE_p_Forms__TForm.getCPtr(form), take_focus);
  }

  public static SWIGTYPE_p_Forms__TForm find_tform(String caption) {
    long cPtr = IdaJavaJNI.find_tform(caption);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm get_current_tform() {
    long cPtr = IdaJavaJNI.get_current_tform();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Controls__TCustomControl create_custom_viewer(String title, SWIGTYPE_p_Controls__TWinControl parent, SWIGTYPE_p_place_t minplace, SWIGTYPE_p_place_t maxplace, SWIGTYPE_p_place_t curplace, int y, SWIGTYPE_p_void ud) {
    long cPtr = IdaJavaJNI.create_custom_viewer(title, SWIGTYPE_p_Controls__TWinControl.getCPtr(parent), SWIGTYPE_p_place_t.getCPtr(minplace), SWIGTYPE_p_place_t.getCPtr(maxplace), SWIGTYPE_p_place_t.getCPtr(curplace), y, SWIGTYPE_p_void.getCPtr(ud));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Controls__TCustomControl(cPtr, false);
  }

  public static void refresh_custom_viewer(SWIGTYPE_p_Controls__TCustomControl custom_viewer) {
    IdaJavaJNI.refresh_custom_viewer(SWIGTYPE_p_Controls__TCustomControl.getCPtr(custom_viewer));
  }

  public static void destroy_custom_viewer(SWIGTYPE_p_Controls__TCustomControl custom_viewer) {
    IdaJavaJNI.destroy_custom_viewer(SWIGTYPE_p_Controls__TCustomControl.getCPtr(custom_viewer));
  }

  public static boolean jumpto(SWIGTYPE_p_Controls__TCustomControl custom_viewer, SWIGTYPE_p_place_t place, int x, int y) {
    return IdaJavaJNI.jumpto__SWIG_2(SWIGTYPE_p_Controls__TCustomControl.getCPtr(custom_viewer), SWIGTYPE_p_place_t.getCPtr(place), x, y);
  }

  public static SWIGTYPE_p_place_t get_custom_viewer_place(SWIGTYPE_p_Controls__TCustomControl custom_viewer, boolean mouse, int[] x, int[] y) {
    long cPtr = IdaJavaJNI.get_custom_viewer_place(SWIGTYPE_p_Controls__TCustomControl.getCPtr(custom_viewer), mouse, x, y);
    return (cPtr == 0) ? null : new SWIGTYPE_p_place_t(cPtr, false);
  }

  public static void set_custom_viewer_popup_menu(SWIGTYPE_p_Controls__TCustomControl custom_viewer, SWIGTYPE_p_Menus__TPopupMenu menu) {
    IdaJavaJNI.set_custom_viewer_popup_menu(SWIGTYPE_p_Controls__TCustomControl.getCPtr(custom_viewer), SWIGTYPE_p_Menus__TPopupMenu.getCPtr(menu));
  }

  public static void add_custom_viewer_popup_item(SWIGTYPE_p_Controls__TCustomControl custom_viewer, String title, String hotkey, SWIGTYPE_p_f_p_void__bool cb, SWIGTYPE_p_void ud) {
    IdaJavaJNI.add_custom_viewer_popup_item(SWIGTYPE_p_Controls__TCustomControl.getCPtr(custom_viewer), title, hotkey, SWIGTYPE_p_f_p_void__bool.getCPtr(cb), SWIGTYPE_p_void.getCPtr(ud));
  }

  public static void set_custom_viewer_handlers(SWIGTYPE_p_Controls__TCustomControl custom_viewer, SWIGTYPE_p_f_p_Controls__TCustomControl_int_int_p_void__bool keyboard_handler, SWIGTYPE_p_f_p_Controls__TCustomControl_p_void__void popup_handler, SWIGTYPE_p_f_p_Controls__TCustomControl_int_p_void__bool dblclick_handler, SWIGTYPE_p_f_p_Controls__TCustomControl_p_void__void curpos_handler, SWIGTYPE_p_f_p_Controls__TCustomControl_p_void__void close_handler, SWIGTYPE_p_void user_data) {
    IdaJavaJNI.set_custom_viewer_handlers(SWIGTYPE_p_Controls__TCustomControl.getCPtr(custom_viewer), SWIGTYPE_p_f_p_Controls__TCustomControl_int_int_p_void__bool.getCPtr(keyboard_handler), SWIGTYPE_p_f_p_Controls__TCustomControl_p_void__void.getCPtr(popup_handler), SWIGTYPE_p_f_p_Controls__TCustomControl_int_p_void__bool.getCPtr(dblclick_handler), SWIGTYPE_p_f_p_Controls__TCustomControl_p_void__void.getCPtr(curpos_handler), SWIGTYPE_p_f_p_Controls__TCustomControl_p_void__void.getCPtr(close_handler), SWIGTYPE_p_void.getCPtr(user_data));
  }

  public static SWIGTYPE_p_void set_custom_viewer_handler(SWIGTYPE_p_Controls__TCustomControl custom_viewer, custom_viewer_handler_id_t handler_id, SWIGTYPE_p_void handler_or_data) {
    long cPtr = IdaJavaJNI.set_custom_viewer_handler(SWIGTYPE_p_Controls__TCustomControl.getCPtr(custom_viewer), handler_id.swigValue(), SWIGTYPE_p_void.getCPtr(handler_or_data));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static String get_custom_viewer_curline(SWIGTYPE_p_Controls__TCustomControl custom_viewer, boolean mouse) {
    return IdaJavaJNI.get_custom_viewer_curline(SWIGTYPE_p_Controls__TCustomControl.getCPtr(custom_viewer), mouse);
  }

  public static SWIGTYPE_p_Controls__TCustomControl get_current_viewer() {
    long cPtr = IdaJavaJNI.get_current_viewer();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Controls__TCustomControl(cPtr, false);
  }

  public static void set_custom_viewer_range(SWIGTYPE_p_Controls__TCustomControl custom_viewer, SWIGTYPE_p_place_t minplace, SWIGTYPE_p_place_t maxplace) {
    IdaJavaJNI.set_custom_viewer_range(SWIGTYPE_p_Controls__TCustomControl.getCPtr(custom_viewer), SWIGTYPE_p_place_t.getCPtr(minplace), SWIGTYPE_p_place_t.getCPtr(maxplace));
  }

  public static boolean is_idaview(SWIGTYPE_p_Controls__TCustomControl v) {
    return IdaJavaJNI.is_idaview(SWIGTYPE_p_Controls__TCustomControl.getCPtr(v));
  }

  public static boolean readsel2(SWIGTYPE_p_Controls__TCustomControl v, SWIGTYPE_p_twinpos_t p1, SWIGTYPE_p_twinpos_t p2) {
    return IdaJavaJNI.readsel2(SWIGTYPE_p_Controls__TCustomControl.getCPtr(v), SWIGTYPE_p_twinpos_t.getCPtr(p1), SWIGTYPE_p_twinpos_t.getCPtr(p2));
  }

  public static void clearBreak() {
    IdaJavaJNI.clearBreak();
  }

  public static void setBreak() {
    IdaJavaJNI.setBreak();
  }

  public static boolean wasBreak() {
    return IdaJavaJNI.wasBreak();
  }

  public static boolean ui_load_new_file(String filename, SWIGTYPE_p_linput_t li, int neflags) {
    return IdaJavaJNI.ui_load_new_file(filename, SWIGTYPE_p_linput_t.getCPtr(li), neflags);
  }

  public static boolean ui_run_debugger(String dbgopts, String exename, int argc, SWIGTYPE_p_p_char argv) {
    return IdaJavaJNI.ui_run_debugger(dbgopts, exename, argc, SWIGTYPE_p_p_char.getCPtr(argv));
  }

  public static int add_idc_hotkey(String hotkey, String idcfunc) {
    return IdaJavaJNI.add_idc_hotkey(hotkey, idcfunc);
  }

  public static boolean del_idc_hotkey(String hotkey) {
    return IdaJavaJNI.del_idc_hotkey(hotkey);
  }

  public static SWIGTYPE_p_Forms__TForm open_exports_window(long ea) {
    long cPtr = IdaJavaJNI.open_exports_window(ea);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_imports_window(long ea) {
    long cPtr = IdaJavaJNI.open_imports_window(ea);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_names_window(long ea) {
    long cPtr = IdaJavaJNI.open_names_window(ea);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_funcs_window(long ea) {
    long cPtr = IdaJavaJNI.open_funcs_window(ea);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_strings_window(long ea, long selstart, long selend) {
    long cPtr = IdaJavaJNI.open_strings_window__SWIG_0(ea, selstart, selend);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_strings_window(long ea, long selstart) {
    long cPtr = IdaJavaJNI.open_strings_window__SWIG_1(ea, selstart);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_strings_window(long ea) {
    long cPtr = IdaJavaJNI.open_strings_window__SWIG_2(ea);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_segments_window(long ea) {
    long cPtr = IdaJavaJNI.open_segments_window(ea);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_segregs_window(long ea) {
    long cPtr = IdaJavaJNI.open_segregs_window(ea);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_selectors_window() {
    long cPtr = IdaJavaJNI.open_selectors_window();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_signatures_window() {
    long cPtr = IdaJavaJNI.open_signatures_window();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_tils_window() {
    long cPtr = IdaJavaJNI.open_tils_window();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_loctypes_window(int ordinal) {
    long cPtr = IdaJavaJNI.open_loctypes_window(ordinal);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_calls_window(long ea) {
    long cPtr = IdaJavaJNI.open_calls_window(ea);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_problems_window(long ea) {
    long cPtr = IdaJavaJNI.open_problems_window(ea);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_bpts_window(long ea) {
    long cPtr = IdaJavaJNI.open_bpts_window(ea);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_threads_window() {
    long cPtr = IdaJavaJNI.open_threads_window();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_modules_window() {
    long cPtr = IdaJavaJNI.open_modules_window();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_trace_window() {
    long cPtr = IdaJavaJNI.open_trace_window();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_stack_window() {
    long cPtr = IdaJavaJNI.open_stack_window();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_xrefs_window(long ea) {
    long cPtr = IdaJavaJNI.open_xrefs_window(ea);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_frame_window(SWIGTYPE_p_func_t pfn, long offset) {
    long cPtr = IdaJavaJNI.open_frame_window(SWIGTYPE_p_func_t.getCPtr(pfn), offset);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_navband_window(long ea, int zoom) {
    long cPtr = IdaJavaJNI.open_navband_window(ea, zoom);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_enums_window(long const_id) {
    long cPtr = IdaJavaJNI.open_enums_window__SWIG_0(const_id);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_enums_window() {
    long cPtr = IdaJavaJNI.open_enums_window__SWIG_1();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_structs_window(long id, long offset) {
    long cPtr = IdaJavaJNI.open_structs_window__SWIG_0(id, offset);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_structs_window(long id) {
    long cPtr = IdaJavaJNI.open_structs_window__SWIG_1(id);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_structs_window() {
    long cPtr = IdaJavaJNI.open_structs_window__SWIG_2();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_disasm_window(String window_title, SWIGTYPE_p_areavec_t ranges) {
    long cPtr = IdaJavaJNI.open_disasm_window__SWIG_0(window_title, SWIGTYPE_p_areavec_t.getCPtr(ranges));
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_disasm_window(String window_title) {
    long cPtr = IdaJavaJNI.open_disasm_window__SWIG_1(window_title);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_hexdump_window(String window_title) {
    long cPtr = IdaJavaJNI.open_hexdump_window(window_title);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static SWIGTYPE_p_Forms__TForm open_notepad_window() {
    long cPtr = IdaJavaJNI.open_notepad_window();
    return (cPtr == 0) ? null : new SWIGTYPE_p_Forms__TForm(cPtr, false);
  }

  public static String choose_idasgn() {
    return IdaJavaJNI.choose_idasgn();
  }

  public static boolean choose_til(String buf, long bufsize) {
    return IdaJavaJNI.choose_til(buf, bufsize);
  }

  public static long choose_entry(String title) {
    return IdaJavaJNI.choose_entry(title);
  }

  public static long choose_name(String title) {
    return IdaJavaJNI.choose_name(title);
  }

  public static long choose_stkvar_xref(SWIGTYPE_p_func_t pfn, SWIGTYPE_p_member_t mptr) {
    return IdaJavaJNI.choose_stkvar_xref(SWIGTYPE_p_func_t.getCPtr(pfn), SWIGTYPE_p_member_t.getCPtr(mptr));
  }

  public static long choose_xref(long to) {
    return IdaJavaJNI.choose_xref(to);
  }

  public static SWIGTYPE_p_enum_t choose_enum(String title, SWIGTYPE_p_enum_t default_id) {
    return new SWIGTYPE_p_enum_t(IdaJavaJNI.choose_enum(title, SWIGTYPE_p_enum_t.getCPtr(default_id)), true);
  }

  public static SWIGTYPE_p_enum_t choose_enum_by_value(String title, SWIGTYPE_p_enum_t default_id, long value, SWIGTYPE_p_unsigned_char serial) {
    return new SWIGTYPE_p_enum_t(IdaJavaJNI.choose_enum_by_value(title, SWIGTYPE_p_enum_t.getCPtr(default_id), value, SWIGTYPE_p_unsigned_char.getCPtr(serial)), true);
  }

  public static SWIGTYPE_p_func_t choose_func(String title, long default_ea) {
    long cPtr = IdaJavaJNI.choose_func(title, default_ea);
    return (cPtr == 0) ? null : new SWIGTYPE_p_func_t(cPtr, false);
  }

  public static SWIGTYPE_p_segment_t choose_segm(String title, long default_ea) {
    long cPtr = IdaJavaJNI.choose_segm(title, default_ea);
    return (cPtr == 0) ? null : new SWIGTYPE_p_segment_t(cPtr, false);
  }

  public static SWIGTYPE_p_segreg_t choose_segreg(String title) {
    long cPtr = IdaJavaJNI.choose_segreg(title);
    return (cPtr == 0) ? null : new SWIGTYPE_p_segreg_t(cPtr, false);
  }

  public static SWIGTYPE_p_struc_t choose_struc(String title) {
    long cPtr = IdaJavaJNI.choose_struc(title);
    return (cPtr == 0) ? null : new SWIGTYPE_p_struc_t(cPtr, false);
  }

  public static boolean add_chooser_command(String chooser_caption, String cmd_caption, SWIGTYPE_p_chooser_cb_t chooser_cb, int menu_index, int icon, int flags) {
    return IdaJavaJNI.add_chooser_command__SWIG_0(chooser_caption, cmd_caption, SWIGTYPE_p_chooser_cb_t.getCPtr(chooser_cb), menu_index, icon, flags);
  }

  public static boolean add_chooser_command(String chooser_caption, String cmd_caption, SWIGTYPE_p_chooser_cb_t chooser_cb, int menu_index, int icon) {
    return IdaJavaJNI.add_chooser_command__SWIG_1(chooser_caption, cmd_caption, SWIGTYPE_p_chooser_cb_t.getCPtr(chooser_cb), menu_index, icon);
  }

  public static boolean add_chooser_command(String chooser_caption, String cmd_caption, SWIGTYPE_p_chooser_cb_t chooser_cb, int menu_index) {
    return IdaJavaJNI.add_chooser_command__SWIG_2(chooser_caption, cmd_caption, SWIGTYPE_p_chooser_cb_t.getCPtr(chooser_cb), menu_index);
  }

  public static boolean add_chooser_command(String chooser_caption, String cmd_caption, SWIGTYPE_p_chooser_cb_t chooser_cb) {
    return IdaJavaJNI.add_chooser_command__SWIG_3(chooser_caption, cmd_caption, SWIGTYPE_p_chooser_cb_t.getCPtr(chooser_cb));
  }

  public static SWIGTYPE_p_void get_chooser_obj(String chooser_caption) {
    long cPtr = IdaJavaJNI.get_chooser_obj(chooser_caption);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static boolean enable_chooser_item_attrs(String chooser_caption, boolean enable) {
    return IdaJavaJNI.enable_chooser_item_attrs(chooser_caption, enable);
  }

  public static void show_wait_box_v(String format, SWIGTYPE_p_va_list va) {
    IdaJavaJNI.show_wait_box_v(format, SWIGTYPE_p_va_list.getCPtr(va));
  }

  public static void show_wait_box(String format) {
    IdaJavaJNI.show_wait_box(format);
  }

  public static void hide_wait_box() {
    IdaJavaJNI.hide_wait_box();
  }

  public static void replace_wait_box(String format) {
    IdaJavaJNI.replace_wait_box(format);
  }

  public static int AskUsingForm_cv(String format, SWIGTYPE_p_va_list va) {
    return IdaJavaJNI.AskUsingForm_cv(format, SWIGTYPE_p_va_list.getCPtr(va));
  }

  public static void close_form(SWIGTYPE_p_p_TView fields, int is_ok) {
    IdaJavaJNI.close_form(SWIGTYPE_p_p_TView.getCPtr(fields), is_ok);
  }

  public static void beep(beep_t beep_type) {
    IdaJavaJNI.beep__SWIG_0(beep_type.swigValue());
  }

  public static void beep() {
    IdaJavaJNI.beep__SWIG_1();
  }

  public static int askbuttons_cv(String Yes, String No, String Cancel, int deflt, String format, SWIGTYPE_p_va_list va) {
    return IdaJavaJNI.askbuttons_cv(Yes, No, Cancel, deflt, format, SWIGTYPE_p_va_list.getCPtr(va));
  }

  public static String askfile_cv(int savefile, String defval, String format, SWIGTYPE_p_va_list va) {
    return IdaJavaJNI.askfile_cv(savefile, defval, format, SWIGTYPE_p_va_list.getCPtr(va));
  }

  public static void ask_for_feedback(String format) {
    IdaJavaJNI.ask_for_feedback(format);
  }

  public static String askident(String defval, String format) {
    return IdaJavaJNI.askident(defval, format);
  }

  public static int askseg(SWIGTYPE_p_unsigned_int sel, String format) {
    return IdaJavaJNI.askseg(SWIGTYPE_p_unsigned_int.getCPtr(sel), format);
  }

  public static int asklong(SWIGTYPE_p_int value, String format) {
    return IdaJavaJNI.asklong(SWIGTYPE_p_int.getCPtr(value), format);
  }

  public static String vaskstr(int hist, String defval, String format, SWIGTYPE_p_va_list va) {
    return IdaJavaJNI.vaskstr(hist, defval, format, SWIGTYPE_p_va_list.getCPtr(va));
  }

  public static String vasktext(long size, String answer, String defval, String format, SWIGTYPE_p_va_list va) {
    return IdaJavaJNI.vasktext(size, answer, defval, format, SWIGTYPE_p_va_list.getCPtr(va));
  }

  public static void vwarning(String format, SWIGTYPE_p_va_list va) {
    IdaJavaJNI.vwarning(format, SWIGTYPE_p_va_list.getCPtr(va));
  }

  public static void vinfo(String format, SWIGTYPE_p_va_list va) {
    IdaJavaJNI.vinfo(format, SWIGTYPE_p_va_list.getCPtr(va));
  }

  public static void vnomem(String format, SWIGTYPE_p_va_list va) {
    IdaJavaJNI.vnomem(format, SWIGTYPE_p_va_list.getCPtr(va));
  }

  public static int vmsg(String format, SWIGTYPE_p_va_list va) {
    return IdaJavaJNI.vmsg(format, SWIGTYPE_p_va_list.getCPtr(va));
  }

  public static boolean display_copyright_warning() {
    return IdaJavaJNI.display_copyright_warning();
  }

  public static boolean set_xml(String path, String name, int value) {
    return IdaJavaJNI.set_xml__SWIG_1(path, name, value);
  }

  public static void setBatch(int value) {
    IdaJavaJNI.batch_set(value);
  }

  public static int getBatch() {
    return IdaJavaJNI.batch_get();
  }

  public static void setErrorexit(int value) {
    IdaJavaJNI.errorexit_set(value);
  }

  public static int getErrorexit() {
    return IdaJavaJNI.errorexit_get();
  }

  public static void error(String format) {
    IdaJavaJNI.error(format);
  }

  public static void warning(String format) {
    IdaJavaJNI.warning(format);
  }

  public static void info(String format) {
    IdaJavaJNI.info(format);
  }

  public static void nomem(String format) {
    IdaJavaJNI.nomem(format);
  }

  public static int msg(String format) {
    return IdaJavaJNI.msg(format);
  }

  public static int askyn_cv(int deflt, String format, SWIGTYPE_p_va_list va) {
    return IdaJavaJNI.askyn_cv(deflt, format, SWIGTYPE_p_va_list.getCPtr(va));
  }

  public static int askyn_c(int deflt, String format) {
    return IdaJavaJNI.askyn_c(deflt, format);
  }

  public static int askbuttons_c(String Yes, String No, String Cancel, int deflt, String format) {
    return IdaJavaJNI.askbuttons_c(Yes, No, Cancel, deflt, format);
  }

  public static String askstr(int hist, String defval, String format) {
    return IdaJavaJNI.askstr(hist, defval, format);
  }

  public static String askfile_c(int savefile, String defval, String format) {
    return IdaJavaJNI.askfile_c(savefile, defval, format);
  }

  public static int enumerate_files(String answer, long answer_size, String path, String fname, SWIGTYPE_p_f_p_q_const__char_p_void__int func, SWIGTYPE_p_void ud) {
    return IdaJavaJNI.enumerate_files(answer, answer_size, path, fname, SWIGTYPE_p_f_p_q_const__char_p_void__int.getCPtr(func), SWIGTYPE_p_void.getCPtr(ud));
  }

  public static int enumerate_system_files(String answer, long answer_size, String subdir, String fname, SWIGTYPE_p_f_p_q_const__char_p_void__int func, SWIGTYPE_p_void ud) {
    return IdaJavaJNI.enumerate_system_files(answer, answer_size, subdir, fname, SWIGTYPE_p_f_p_q_const__char_p_void__int.getCPtr(func), SWIGTYPE_p_void.getCPtr(ud));
  }

  public static String idadir(String subdir) {
    return IdaJavaJNI.idadir(subdir);
  }

  public static String getsysfile(String buf, long bufsize, String filename, String subdir) {
    return IdaJavaJNI.getsysfile(buf, bufsize, filename, subdir);
  }

  public static String get_user_idadir() {
    return IdaJavaJNI.get_user_idadir();
  }

  public static SWIGTYPE_p_FILE fopenWT(String file) {
    long cPtr = IdaJavaJNI.fopenWT(file);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static SWIGTYPE_p_FILE fopenWB(String file) {
    long cPtr = IdaJavaJNI.fopenWB(file);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static SWIGTYPE_p_FILE fopenRT(String file) {
    long cPtr = IdaJavaJNI.fopenRT(file);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static SWIGTYPE_p_FILE fopenRB(String file) {
    long cPtr = IdaJavaJNI.fopenRB(file);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static SWIGTYPE_p_FILE fopenM(String file) {
    long cPtr = IdaJavaJNI.fopenM(file);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static SWIGTYPE_p_FILE fopenA(String file) {
    long cPtr = IdaJavaJNI.fopenA(file);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static SWIGTYPE_p_FILE openR(String file) {
    long cPtr = IdaJavaJNI.openR(file);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static SWIGTYPE_p_FILE openRT(String file) {
    long cPtr = IdaJavaJNI.openRT(file);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static SWIGTYPE_p_FILE openM(String file) {
    long cPtr = IdaJavaJNI.openM(file);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static SWIGTYPE_p_FILE ecreate(String file) {
    long cPtr = IdaJavaJNI.ecreate(file);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static SWIGTYPE_p_FILE ecreateT(String file) {
    long cPtr = IdaJavaJNI.ecreateT(file);
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static void eclose(SWIGTYPE_p_FILE fp) {
    IdaJavaJNI.eclose(SWIGTYPE_p_FILE.getCPtr(fp));
  }

  public static void eread(SWIGTYPE_p_FILE fp, SWIGTYPE_p_void buf, int size) {
    IdaJavaJNI.eread(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_void.getCPtr(buf), size);
  }

  public static void ewrite(SWIGTYPE_p_FILE fp, SWIGTYPE_p_void buf, int size) {
    IdaJavaJNI.ewrite(SWIGTYPE_p_FILE.getCPtr(fp), SWIGTYPE_p_void.getCPtr(buf), size);
  }

  public static void eseek(SWIGTYPE_p_FILE fp, int pos) {
    IdaJavaJNI.eseek(SWIGTYPE_p_FILE.getCPtr(fp), pos);
  }

  public static long efilelength(SWIGTYPE_p_FILE fp) {
    return IdaJavaJNI.efilelength(SWIGTYPE_p_FILE.getCPtr(fp));
  }

  public static void echsize(SWIGTYPE_p_FILE fp, long size) {
    IdaJavaJNI.echsize(SWIGTYPE_p_FILE.getCPtr(fp), size);
  }

  public static SWIGTYPE_p_ulonglong getdspace(String path) {
    return new SWIGTYPE_p_ulonglong(IdaJavaJNI.getdspace(path), true);
  }

  public static ioport_t find_ioport(ioport_t ports, long numports, long address) {
    long cPtr = IdaJavaJNI.find_ioport(ioport_t.getCPtr(ports), ports, numports, address);
    return (cPtr == 0) ? null : new ioport_t(cPtr, false);
  }

  public static ioport_bit_t find_ioport_bit(ioport_t ports, long numports, long address, long bit) {
    long cPtr = IdaJavaJNI.find_ioport_bit(ioport_t.getCPtr(ports), ports, numports, address, bit);
    return (cPtr == 0) ? null : new ioport_bit_t(cPtr, false);
  }

  public static void free_ioports(ioport_t ports, long numports) {
    IdaJavaJNI.free_ioports(ioport_t.getCPtr(ports), ports, numports);
  }

  public static int call_system(String command) {
    return IdaJavaJNI.call_system(command);
  }

  public static int set_thread_priority(int pclass, int delta) {
    return IdaJavaJNI.set_thread_priority(pclass, delta);
  }

  public static void lread(SWIGTYPE_p_linput_t li, SWIGTYPE_p_void buf, long size) {
    IdaJavaJNI.lread(SWIGTYPE_p_linput_t.getCPtr(li), SWIGTYPE_p_void.getCPtr(buf), size);
  }

  public static int qlread(SWIGTYPE_p_linput_t li, SWIGTYPE_p_void buf, long size) {
    return IdaJavaJNI.qlread(SWIGTYPE_p_linput_t.getCPtr(li), SWIGTYPE_p_void.getCPtr(buf), size);
  }

  public static String qlgets(String s, long len, SWIGTYPE_p_linput_t li) {
    return IdaJavaJNI.qlgets(s, len, SWIGTYPE_p_linput_t.getCPtr(li));
  }

  public static int qlgetc(SWIGTYPE_p_linput_t li) {
    return IdaJavaJNI.qlgetc(SWIGTYPE_p_linput_t.getCPtr(li));
  }

  public static int lreadbytes(SWIGTYPE_p_linput_t li, SWIGTYPE_p_void buf, long size, boolean mf) {
    return IdaJavaJNI.lreadbytes(SWIGTYPE_p_linput_t.getCPtr(li), SWIGTYPE_p_void.getCPtr(buf), size, mf);
  }

  public static int lread2bytes(SWIGTYPE_p_linput_t li, SWIGTYPE_p_short res, boolean mf) {
    return IdaJavaJNI.lread2bytes__SWIG_0(SWIGTYPE_p_linput_t.getCPtr(li), SWIGTYPE_p_short.getCPtr(res), mf);
  }

  public static int lread2bytes(SWIGTYPE_p_linput_t li, SWIGTYPE_p_unsigned_short res, boolean mf) {
    return IdaJavaJNI.lread2bytes__SWIG_1(SWIGTYPE_p_linput_t.getCPtr(li), SWIGTYPE_p_unsigned_short.getCPtr(res), mf);
  }

  public static int lread4bytes(SWIGTYPE_p_linput_t li, SWIGTYPE_p_int res, boolean mf) {
    return IdaJavaJNI.lread4bytes__SWIG_0(SWIGTYPE_p_linput_t.getCPtr(li), SWIGTYPE_p_int.getCPtr(res), mf);
  }

  public static int lread4bytes(SWIGTYPE_p_linput_t li, SWIGTYPE_p_unsigned_int res, boolean mf) {
    return IdaJavaJNI.lread4bytes__SWIG_1(SWIGTYPE_p_linput_t.getCPtr(li), SWIGTYPE_p_unsigned_int.getCPtr(res), mf);
  }

  public static int lread8bytes(SWIGTYPE_p_linput_t li, SWIGTYPE_p_longlong res, boolean mf) {
    return IdaJavaJNI.lread8bytes__SWIG_0(SWIGTYPE_p_linput_t.getCPtr(li), SWIGTYPE_p_longlong.getCPtr(res), mf);
  }

  public static int lread8bytes(SWIGTYPE_p_linput_t li, SWIGTYPE_p_ulonglong res, boolean mf) {
    return IdaJavaJNI.lread8bytes__SWIG_1(SWIGTYPE_p_linput_t.getCPtr(li), SWIGTYPE_p_ulonglong.getCPtr(res), mf);
  }

  public static String qlgetz(SWIGTYPE_p_linput_t li, int fpos, String buf, long bufsize) {
    return IdaJavaJNI.qlgetz(SWIGTYPE_p_linput_t.getCPtr(li), fpos, buf, bufsize);
  }

  public static int qlsize(SWIGTYPE_p_linput_t li) {
    return IdaJavaJNI.qlsize(SWIGTYPE_p_linput_t.getCPtr(li));
  }

  public static int qlseek(SWIGTYPE_p_linput_t li, int pos, int whence) {
    return IdaJavaJNI.qlseek__SWIG_0(SWIGTYPE_p_linput_t.getCPtr(li), pos, whence);
  }

  public static int qlseek(SWIGTYPE_p_linput_t li, int pos) {
    return IdaJavaJNI.qlseek__SWIG_1(SWIGTYPE_p_linput_t.getCPtr(li), pos);
  }

  public static int qltell(SWIGTYPE_p_linput_t li) {
    return IdaJavaJNI.qltell(SWIGTYPE_p_linput_t.getCPtr(li));
  }

  public static SWIGTYPE_p_linput_t open_linput(String file, boolean remote) {
    long cPtr = IdaJavaJNI.open_linput(file, remote);
    return (cPtr == 0) ? null : new SWIGTYPE_p_linput_t(cPtr, false);
  }

  public static void close_linput(SWIGTYPE_p_linput_t li) {
    IdaJavaJNI.close_linput(SWIGTYPE_p_linput_t.getCPtr(li));
  }

  public static SWIGTYPE_p_FILE qlfile(SWIGTYPE_p_linput_t li) {
    long cPtr = IdaJavaJNI.qlfile(SWIGTYPE_p_linput_t.getCPtr(li));
    return (cPtr == 0) ? null : new SWIGTYPE_p_FILE(cPtr, false);
  }

  public static SWIGTYPE_p_linput_t make_linput(SWIGTYPE_p_FILE fp) {
    long cPtr = IdaJavaJNI.make_linput(SWIGTYPE_p_FILE.getCPtr(fp));
    return (cPtr == 0) ? null : new SWIGTYPE_p_linput_t(cPtr, false);
  }

  public static void unmake_linput(SWIGTYPE_p_linput_t li) {
    IdaJavaJNI.unmake_linput(SWIGTYPE_p_linput_t.getCPtr(li));
  }

  public static SWIGTYPE_p_linput_t create_generic_linput(generic_linput_t gl) {
    long cPtr = IdaJavaJNI.create_generic_linput(generic_linput_t.getCPtr(gl), gl);
    return (cPtr == 0) ? null : new SWIGTYPE_p_linput_t(cPtr, false);
  }

  public static SWIGTYPE_p_linput_t create_memory_linput(long start, long size) {
    long cPtr = IdaJavaJNI.create_memory_linput(start, size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_linput_t(cPtr, false);
  }

  public static linput_type_t get_linput_type(SWIGTYPE_p_linput_t li) {
    return linput_type_t.swigToEnum(IdaJavaJNI.get_linput_type(SWIGTYPE_p_linput_t.getCPtr(li)));
  }

  public static String getParameter(String key) {
    return IdaJavaJNI.getParameter(key);
  }

  public static int getIdaWindowHandle() {
    return IdaJavaJNI.getIdaWindowHandle();
  }

  public static boolean initIdaEmbeddedWindow(SWIGTYPE_p_Forms__TForm form) {
    return IdaJavaJNI.initIdaEmbeddedWindow(SWIGTYPE_p_Forms__TForm.getCPtr(form));
  }

  public static int getInternalHandle(int handle) {
    return IdaJavaJNI.getInternalHandle(handle);
  }

  public static void sayHello() {
    IdaJavaJNI.sayHello();
  }

  public static String getIdbPath() {
    return IdaJavaJNI.getIdbPath();
  }

  public static boolean openDatabase(String fileName) {
    return IdaJavaJNI.openDatabase(fileName);
  }

  public static void closeDatabase() {
    IdaJavaJNI.closeDatabase();
  }

  public static boolean addMenuItem(String menupath, String name, String hotkey, int flags, IdaMenuItemListener listener) {
    return IdaJavaJNI.addMenuItem(menupath, name, hotkey, flags, IdaMenuItemListener.getCPtr(listener), listener);
  }

}
