/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class idc_value_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public idc_value_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(idc_value_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_idc_value_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVtype(char value) {
    IdaJavaJNI.idc_value_t_vtype_set(swigCPtr, this, value);
  }

  public char getVtype() {
    return IdaJavaJNI.idc_value_t_vtype_get(swigCPtr, this);
  }

  public void setStr(String value) {
    IdaJavaJNI.idc_value_t_str_set(swigCPtr, this, value);
  }

  public String getStr() {
    return IdaJavaJNI.idc_value_t_str_get(swigCPtr, this);
  }

  public void setNum(int value) {
    IdaJavaJNI.idc_value_t_num_set(swigCPtr, this, value);
  }

  public int getNum() {
    return IdaJavaJNI.idc_value_t_num_get(swigCPtr, this);
  }

  public void setE(int[] value) {
    IdaJavaJNI.idc_value_t_e_set(swigCPtr, this, value);
  }

  public int[] getE() {
    return IdaJavaJNI.idc_value_t_e_get(swigCPtr, this);
  }

  public void setObj(SWIGTYPE_p_idc_object_t value) {
    IdaJavaJNI.idc_value_t_obj_set(swigCPtr, this, SWIGTYPE_p_idc_object_t.getCPtr(value));
  }

  public SWIGTYPE_p_idc_object_t getObj() {
    long cPtr = IdaJavaJNI.idc_value_t_obj_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_idc_object_t(cPtr, false);
  }

  public void setFuncidx(int value) {
    IdaJavaJNI.idc_value_t_funcidx_set(swigCPtr, this, value);
  }

  public int getFuncidx() {
    return IdaJavaJNI.idc_value_t_funcidx_get(swigCPtr, this);
  }

  public void setPvoid(SWIGTYPE_p_void value) {
    IdaJavaJNI.idc_value_t_pvoid_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPvoid() {
    long cPtr = IdaJavaJNI.idc_value_t_pvoid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setI64(SWIGTYPE_p_longlong value) {
    IdaJavaJNI.idc_value_t_i64_set(swigCPtr, this, SWIGTYPE_p_longlong.getCPtr(value));
  }

  public SWIGTYPE_p_longlong getI64() {
    return new SWIGTYPE_p_longlong(IdaJavaJNI.idc_value_t_i64_get(swigCPtr, this), true);
  }

  public void setReserve(short[] value) {
    IdaJavaJNI.idc_value_t_reserve_set(swigCPtr, this, value);
  }

  public short[] getReserve() {
    return IdaJavaJNI.idc_value_t_reserve_get(swigCPtr, this);
  }

  public idc_value_t(int n) {
    this(IdaJavaJNI.new_idc_value_t__SWIG_0(n), true);
  }

  public idc_value_t() {
    this(IdaJavaJNI.new_idc_value_t__SWIG_1(), true);
  }

  public idc_value_t(idc_value_t r) {
    this(IdaJavaJNI.new_idc_value_t__SWIG_2(idc_value_t.getCPtr(r), r), true);
  }

  public idc_value_t(String _str) {
    this(IdaJavaJNI.new_idc_value_t__SWIG_3(_str), true);
  }

  public idc_value_t(SWIGTYPE_p__qstringT_char_t _str) {
    this(IdaJavaJNI.new_idc_value_t__SWIG_4(SWIGTYPE_p__qstringT_char_t.getCPtr(_str)), true);
  }

  public void clear() {
    IdaJavaJNI.idc_value_t_clear(swigCPtr, this);
  }

  public idc_value_t __assign__(idc_value_t r) {
    return new idc_value_t(IdaJavaJNI.idc_value_t___assign__(swigCPtr, this, idc_value_t.getCPtr(r), r), false);
  }

  public SWIGTYPE_p__qstringT_char_t qstr() {
    return new SWIGTYPE_p__qstringT_char_t(IdaJavaJNI.idc_value_t_qstr__SWIG_0(swigCPtr, this), false);
  }

  public String c_str() {
    return IdaJavaJNI.idc_value_t_c_str(swigCPtr, this);
  }

  public SWIGTYPE_p_unsigned_char u_str() {
    long cPtr = IdaJavaJNI.idc_value_t_u_str(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void swap(idc_value_t v) {
    IdaJavaJNI.idc_value_t_swap(swigCPtr, this, idc_value_t.getCPtr(v), v);
  }

  public boolean is_zero() {
    return IdaJavaJNI.idc_value_t_is_zero(swigCPtr, this);
  }

  public boolean is_convertible() {
    return IdaJavaJNI.idc_value_t_is_convertible(swigCPtr, this);
  }

  public void _create_empty_string() {
    IdaJavaJNI.idc_value_t__create_empty_string(swigCPtr, this);
  }

  public void _set_string(String str, long len) {
    IdaJavaJNI.idc_value_t__set_string__SWIG_0(swigCPtr, this, str, len);
  }

  public void _set_string(String str) {
    IdaJavaJNI.idc_value_t__set_string__SWIG_1(swigCPtr, this, str);
  }

  public void _set_long(int v) {
    IdaJavaJNI.idc_value_t__set_long(swigCPtr, this, v);
  }

  public void create_empty_string() {
    IdaJavaJNI.idc_value_t_create_empty_string(swigCPtr, this);
  }

  public void set_string(String str, long len) {
    IdaJavaJNI.idc_value_t_set_string__SWIG_0(swigCPtr, this, str, len);
  }

  public void set_string(String str) {
    IdaJavaJNI.idc_value_t_set_string__SWIG_1(swigCPtr, this, str);
  }

  public void set_long(int v) {
    IdaJavaJNI.idc_value_t_set_long(swigCPtr, this, v);
  }

  public void set_pvoid(SWIGTYPE_p_void p) {
    IdaJavaJNI.idc_value_t_set_pvoid(swigCPtr, this, SWIGTYPE_p_void.getCPtr(p));
  }

  public void set_int64(SWIGTYPE_p_longlong v) {
    IdaJavaJNI.idc_value_t_set_int64(swigCPtr, this, SWIGTYPE_p_longlong.getCPtr(v));
  }

}
