/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class idd_opinfo_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public idd_opinfo_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(idd_opinfo_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_idd_opinfo_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAddr(long value) {
    IdaJavaJNI.idd_opinfo_t_addr_set(swigCPtr, this, value);
  }

  public long getAddr() {
    return IdaJavaJNI.idd_opinfo_t_addr_get(swigCPtr, this);
  }

  public void setValue(long value) {
    IdaJavaJNI.idd_opinfo_t_value_set(swigCPtr, this, value);
  }

  public long getValue() {
    return IdaJavaJNI.idd_opinfo_t_value_get(swigCPtr, this);
  }

  public void setModified(boolean value) {
    IdaJavaJNI.idd_opinfo_t_modified_set(swigCPtr, this, value);
  }

  public boolean getModified() {
    return IdaJavaJNI.idd_opinfo_t_modified_get(swigCPtr, this);
  }

  public idd_opinfo_t() {
    this(IdaJavaJNI.new_idd_opinfo_t(), true);
  }

}
