/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class incrementer_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public incrementer_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(incrementer_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_incrementer_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public incrementer_t(SWIGTYPE_p_hit_counter_t _ctr) {
    this(IdaJavaJNI.new_incrementer_t(SWIGTYPE_p_hit_counter_t.getCPtr(_ctr)), true);
  }

  public void failed() {
    IdaJavaJNI.incrementer_t_failed(swigCPtr, this);
  }

}
