/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class ioport_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ioport_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ioport_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_ioport_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAddress(long value) {
    IdaJavaJNI.ioport_t_address_set(swigCPtr, this, value);
  }

  public long getAddress() {
    return IdaJavaJNI.ioport_t_address_get(swigCPtr, this);
  }

  public void setName(String value) {
    IdaJavaJNI.ioport_t_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return IdaJavaJNI.ioport_t_name_get(swigCPtr, this);
  }

  public void setCmt(String value) {
    IdaJavaJNI.ioport_t_cmt_set(swigCPtr, this, value);
  }

  public String getCmt() {
    return IdaJavaJNI.ioport_t_cmt_get(swigCPtr, this);
  }

  public void setBits(SWIGTYPE_p_a_16__ioport_bit_t value) {
    IdaJavaJNI.ioport_t_bits_set(swigCPtr, this, SWIGTYPE_p_a_16__ioport_bit_t.getCPtr(value));
  }

  public SWIGTYPE_p_a_16__ioport_bit_t getBits() {
    long cPtr = IdaJavaJNI.ioport_t_bits_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_a_16__ioport_bit_t(cPtr, false);
  }

  public void setUserdata(SWIGTYPE_p_void value) {
    IdaJavaJNI.ioport_t_userdata_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserdata() {
    long cPtr = IdaJavaJNI.ioport_t_userdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public ioport_t() {
    this(IdaJavaJNI.new_ioport_t(), true);
  }

}
