/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class launch_process_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public launch_process_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(launch_process_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_launch_process_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCb(long value) {
    IdaJavaJNI.launch_process_t_cb_set(swigCPtr, this, value);
  }

  public long getCb() {
    return IdaJavaJNI.launch_process_t_cb_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    IdaJavaJNI.launch_process_t_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return IdaJavaJNI.launch_process_t_flags_get(swigCPtr, this);
  }

  public void setPath(String value) {
    IdaJavaJNI.launch_process_t_path_set(swigCPtr, this, value);
  }

  public String getPath() {
    return IdaJavaJNI.launch_process_t_path_get(swigCPtr, this);
  }

  public void setArgs(String value) {
    IdaJavaJNI.launch_process_t_args_set(swigCPtr, this, value);
  }

  public String getArgs() {
    return IdaJavaJNI.launch_process_t_args_get(swigCPtr, this);
  }

  public void setIn_handle(int value) {
    IdaJavaJNI.launch_process_t_in_handle_set(swigCPtr, this, value);
  }

  public int getIn_handle() {
    return IdaJavaJNI.launch_process_t_in_handle_get(swigCPtr, this);
  }

  public void setOut_handle(int value) {
    IdaJavaJNI.launch_process_t_out_handle_set(swigCPtr, this, value);
  }

  public int getOut_handle() {
    return IdaJavaJNI.launch_process_t_out_handle_get(swigCPtr, this);
  }

  public void setErr_handle(int value) {
    IdaJavaJNI.launch_process_t_err_handle_set(swigCPtr, this, value);
  }

  public int getErr_handle() {
    return IdaJavaJNI.launch_process_t_err_handle_get(swigCPtr, this);
  }

  public launch_process_t() {
    this(IdaJavaJNI.new_launch_process_t(), true);
  }

}
