/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class loader_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public loader_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(loader_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_loader_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVersion(long value) {
    IdaJavaJNI.loader_t_version_set(swigCPtr, this, value);
  }

  public long getVersion() {
    return IdaJavaJNI.loader_t_version_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    IdaJavaJNI.loader_t_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return IdaJavaJNI.loader_t_flags_get(swigCPtr, this);
  }

  public loader_t() {
    this(IdaJavaJNI.new_loader_t(), true);
  }

}
