/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class load_info_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public load_info_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(load_info_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_load_info_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNext(load_info_t value) {
    IdaJavaJNI.load_info_t_next_set(swigCPtr, this, load_info_t.getCPtr(value), value);
  }

  public load_info_t getNext() {
    long cPtr = IdaJavaJNI.load_info_t_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new load_info_t(cPtr, false);
  }

  public void setDllname(String value) {
    IdaJavaJNI.load_info_t_dllname_set(swigCPtr, this, value);
  }

  public String getDllname() {
    return IdaJavaJNI.load_info_t_dllname_get(swigCPtr, this);
  }

  public void setFtypename(String value) {
    IdaJavaJNI.load_info_t_ftypename_set(swigCPtr, this, value);
  }

  public String getFtypename() {
    return IdaJavaJNI.load_info_t_ftypename_get(swigCPtr, this);
  }

  public void setFtype(filetype_t value) {
    IdaJavaJNI.load_info_t_ftype_set(swigCPtr, this, value.swigValue());
  }

  public filetype_t getFtype() {
    return filetype_t.swigToEnum(IdaJavaJNI.load_info_t_ftype_get(swigCPtr, this));
  }

  public void setPri(int value) {
    IdaJavaJNI.load_info_t_pri_set(swigCPtr, this, value);
  }

  public int getPri() {
    return IdaJavaJNI.load_info_t_pri_get(swigCPtr, this);
  }

  public load_info_t() {
    this(IdaJavaJNI.new_load_info_t(), true);
  }

}
