/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class lock_area {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public lock_area(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(lock_area obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_lock_area(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public lock_area(areacb_t _cb, area_t _area) {
    this(IdaJavaJNI.new_lock_area(areacb_t.getCPtr(_cb), _cb, area_t.getCPtr(_area), _area), true);
  }

}
