/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class lock_segment {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public lock_segment(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(lock_segment obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_lock_segment(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public lock_segment(segment_t _segm) {
    this(IdaJavaJNI.new_lock_segment(segment_t.getCPtr(_segm), _segm), true);
  }

}
