/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class MD5Context {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public MD5Context(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(MD5Context obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_MD5Context(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBuf(long[] value) {
    IdaJavaJNI.MD5Context_buf_set(swigCPtr, this, value);
  }

  public long[] getBuf() {
    return IdaJavaJNI.MD5Context_buf_get(swigCPtr, this);
  }

  public void setBits(long[] value) {
    IdaJavaJNI.MD5Context_bits_set(swigCPtr, this, value);
  }

  public long[] getBits() {
    return IdaJavaJNI.MD5Context_bits_get(swigCPtr, this);
  }

  public void setIn(short[] value) {
    IdaJavaJNI.MD5Context_in_set(swigCPtr, this, value);
  }

  public short[] getIn() {
    return IdaJavaJNI.MD5Context_in_get(swigCPtr, this);
  }

  public MD5Context() {
    this(IdaJavaJNI.new_MD5Context(), true);
  }

}
