/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class member_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public member_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(member_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_member_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    IdaJavaJNI.member_t_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return IdaJavaJNI.member_t_id_get(swigCPtr, this);
  }

  public void setSoff(long value) {
    IdaJavaJNI.member_t_soff_set(swigCPtr, this, value);
  }

  public long getSoff() {
    return IdaJavaJNI.member_t_soff_get(swigCPtr, this);
  }

  public void setEoff(long value) {
    IdaJavaJNI.member_t_eoff_set(swigCPtr, this, value);
  }

  public long getEoff() {
    return IdaJavaJNI.member_t_eoff_get(swigCPtr, this);
  }

  public void setFlag(long value) {
    IdaJavaJNI.member_t_flag_set(swigCPtr, this, value);
  }

  public long getFlag() {
    return IdaJavaJNI.member_t_flag_get(swigCPtr, this);
  }

  public void setProps(long value) {
    IdaJavaJNI.member_t_props_set(swigCPtr, this, value);
  }

  public long getProps() {
    return IdaJavaJNI.member_t_props_get(swigCPtr, this);
  }

  public boolean unimem() {
    return IdaJavaJNI.member_t_unimem(swigCPtr, this);
  }

  public boolean has_union() {
    return IdaJavaJNI.member_t_has_union(swigCPtr, this);
  }

  public boolean by_til() {
    return IdaJavaJNI.member_t_by_til(swigCPtr, this);
  }

  public boolean has_ti() {
    return IdaJavaJNI.member_t_has_ti(swigCPtr, this);
  }

  public long get_soff() {
    return IdaJavaJNI.member_t_get_soff(swigCPtr, this);
  }

  public member_t() {
    this(IdaJavaJNI.new_member_t(), true);
  }

}
