/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class module_info_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public module_info_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(module_info_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_module_info_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(String value) {
    IdaJavaJNI.module_info_t_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return IdaJavaJNI.module_info_t_name_get(swigCPtr, this);
  }

  public void setBase(long value) {
    IdaJavaJNI.module_info_t_base_set(swigCPtr, this, value);
  }

  public long getBase() {
    return IdaJavaJNI.module_info_t_base_get(swigCPtr, this);
  }

  public void setSize(long value) {
    IdaJavaJNI.module_info_t_size_set(swigCPtr, this, value);
  }

  public long getSize() {
    return IdaJavaJNI.module_info_t_size_get(swigCPtr, this);
  }

  public void setRebase_to(long value) {
    IdaJavaJNI.module_info_t_rebase_to_set(swigCPtr, this, value);
  }

  public long getRebase_to() {
    return IdaJavaJNI.module_info_t_rebase_to_get(swigCPtr, this);
  }

  public module_info_t() {
    this(IdaJavaJNI.new_module_info_t(), true);
  }

}
