/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public enum name_quick {
  j_ldc_quick(203),
  j_ldcw_quick,
  j_ldc2w_quick,
  j_getfield_quick,
  j_putfield_quick,
  j_getfield2_quick,
  j_putfield2_quick,
  j_getstatic_quick,
  j_putstatic_quick,
  j_getstatic2_quick,
  j_putstatic2_quick,
  j_invokevirtual_quick,
  j_invokenonvirtual_quick,
  j_invokesuper_quick,
  j_invokestatic_quick,
  j_invokeinterface_quick,
  j_invokevirtualobject_quick,
  j_invokeignored_quick,
  j_new_quick,
  j_anewarray_quick,
  j_multianewarray_quick,
  j_checkcast_quick,
  j_instanceof_quick,
  j_invokevirtual_quick_w,
  j_getfield_quick_w,
  j_putfield_quick_w,
  j_quick_last;

  public final int swigValue() {
    return swigValue;
  }

  public static name_quick swigToEnum(int swigValue) {
    name_quick[] swigValues = name_quick.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (name_quick swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + name_quick.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private name_quick() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private name_quick(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private name_quick(name_quick swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

