/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class node_ordering_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public node_ordering_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(node_ordering_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_node_ordering_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void clear() {
    IdaJavaJNI.node_ordering_t_clear(swigCPtr, this);
  }

  public void resize(int n) {
    IdaJavaJNI.node_ordering_t_resize(swigCPtr, this, n);
  }

  public long size() {
    return IdaJavaJNI.node_ordering_t_size(swigCPtr, this);
  }

  public void set(int node, int num) {
    IdaJavaJNI.node_ordering_t_set(swigCPtr, this, node, num);
  }

  public int node(long order) {
    return IdaJavaJNI.node_ordering_t_node(swigCPtr, this, order);
  }

  public node_ordering_t() {
    this(IdaJavaJNI.new_node_ordering_t(), true);
  }

}
