/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class opinfo_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public opinfo_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(opinfo_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_opinfo_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRi(refinfo_t value) {
    IdaJavaJNI.opinfo_t_ri_set(swigCPtr, this, refinfo_t.getCPtr(value), value);
  }

  public refinfo_t getRi() {
    long cPtr = IdaJavaJNI.opinfo_t_ri_get(swigCPtr, this);
    return (cPtr == 0) ? null : new refinfo_t(cPtr, false);
  }

  public void setTid(long value) {
    IdaJavaJNI.opinfo_t_tid_set(swigCPtr, this, value);
  }

  public long getTid() {
    return IdaJavaJNI.opinfo_t_tid_get(swigCPtr, this);
  }

  public void setPath(strpath_t value) {
    IdaJavaJNI.opinfo_t_path_set(swigCPtr, this, strpath_t.getCPtr(value), value);
  }

  public strpath_t getPath() {
    long cPtr = IdaJavaJNI.opinfo_t_path_get(swigCPtr, this);
    return (cPtr == 0) ? null : new strpath_t(cPtr, false);
  }

  public void setStrtype(int value) {
    IdaJavaJNI.opinfo_t_strtype_set(swigCPtr, this, value);
  }

  public int getStrtype() {
    return IdaJavaJNI.opinfo_t_strtype_get(swigCPtr, this);
  }

  public void setEc(enum_const_t value) {
    IdaJavaJNI.opinfo_t_ec_set(swigCPtr, this, enum_const_t.getCPtr(value), value);
  }

  public enum_const_t getEc() {
    long cPtr = IdaJavaJNI.opinfo_t_ec_get(swigCPtr, this);
    return (cPtr == 0) ? null : new enum_const_t(cPtr, false);
  }

  public void setCd(SWIGTYPE_p_custom_data_type_ids_t value) {
    IdaJavaJNI.opinfo_t_cd_set(swigCPtr, this, SWIGTYPE_p_custom_data_type_ids_t.getCPtr(value));
  }

  public SWIGTYPE_p_custom_data_type_ids_t getCd() {
    return new SWIGTYPE_p_custom_data_type_ids_t(IdaJavaJNI.opinfo_t_cd_get(swigCPtr, this), true);
  }

  public opinfo_t() {
    this(IdaJavaJNI.new_opinfo_t(), true);
  }

}
