/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public enum optype_t {
  o_void(0),
  o_reg(1),
  o_mem(2),
  o_phrase(3),
  o_displ(4),
  o_imm(5),
  o_far(6),
  o_near(7),
  o_idpspec0(8),
  o_idpspec1(9),
  o_idpspec2(10),
  o_idpspec3(11),
  o_idpspec4(12),
  o_idpspec5(13),
  o_last(14);

  public final int swigValue() {
    return swigValue;
  }

  public static optype_t swigToEnum(int swigValue) {
    optype_t[] swigValues = optype_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (optype_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + optype_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private optype_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private optype_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private optype_t(optype_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

