/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class plugin_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public plugin_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(plugin_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_plugin_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVersion(int value) {
    IdaJavaJNI.plugin_t_version_set(swigCPtr, this, value);
  }

  public int getVersion() {
    return IdaJavaJNI.plugin_t_version_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    IdaJavaJNI.plugin_t_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return IdaJavaJNI.plugin_t_flags_get(swigCPtr, this);
  }

  public void setComment(String value) {
    IdaJavaJNI.plugin_t_comment_set(swigCPtr, this, value);
  }

  public String getComment() {
    return IdaJavaJNI.plugin_t_comment_get(swigCPtr, this);
  }

  public void setHelp(String value) {
    IdaJavaJNI.plugin_t_help_set(swigCPtr, this, value);
  }

  public String getHelp() {
    return IdaJavaJNI.plugin_t_help_get(swigCPtr, this);
  }

  public void setWanted_name(String value) {
    IdaJavaJNI.plugin_t_wanted_name_set(swigCPtr, this, value);
  }

  public String getWanted_name() {
    return IdaJavaJNI.plugin_t_wanted_name_get(swigCPtr, this);
  }

  public void setWanted_hotkey(String value) {
    IdaJavaJNI.plugin_t_wanted_hotkey_set(swigCPtr, this, value);
  }

  public String getWanted_hotkey() {
    return IdaJavaJNI.plugin_t_wanted_hotkey_get(swigCPtr, this);
  }

  public plugin_t() {
    this(IdaJavaJNI.new_plugin_t(), true);
  }

}
