/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class plugin_info_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public plugin_info_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(plugin_info_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_plugin_info_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNext(plugin_info_t value) {
    IdaJavaJNI.plugin_info_t_next_set(swigCPtr, this, plugin_info_t.getCPtr(value), value);
  }

  public plugin_info_t getNext() {
    long cPtr = IdaJavaJNI.plugin_info_t_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new plugin_info_t(cPtr, false);
  }

  public void setPath(String value) {
    IdaJavaJNI.plugin_info_t_path_set(swigCPtr, this, value);
  }

  public String getPath() {
    return IdaJavaJNI.plugin_info_t_path_get(swigCPtr, this);
  }

  public void setOrg_name(String value) {
    IdaJavaJNI.plugin_info_t_org_name_set(swigCPtr, this, value);
  }

  public String getOrg_name() {
    return IdaJavaJNI.plugin_info_t_org_name_get(swigCPtr, this);
  }

  public void setName(String value) {
    IdaJavaJNI.plugin_info_t_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return IdaJavaJNI.plugin_info_t_name_get(swigCPtr, this);
  }

  public void setOrg_hotkey(int value) {
    IdaJavaJNI.plugin_info_t_org_hotkey_set(swigCPtr, this, value);
  }

  public int getOrg_hotkey() {
    return IdaJavaJNI.plugin_info_t_org_hotkey_get(swigCPtr, this);
  }

  public void setHotkey(int value) {
    IdaJavaJNI.plugin_info_t_hotkey_set(swigCPtr, this, value);
  }

  public int getHotkey() {
    return IdaJavaJNI.plugin_info_t_hotkey_get(swigCPtr, this);
  }

  public void setArg(int value) {
    IdaJavaJNI.plugin_info_t_arg_set(swigCPtr, this, value);
  }

  public int getArg() {
    return IdaJavaJNI.plugin_info_t_arg_get(swigCPtr, this);
  }

  public void setEntry(plugin_t value) {
    IdaJavaJNI.plugin_info_t_entry_set(swigCPtr, this, plugin_t.getCPtr(value), value);
  }

  public plugin_t getEntry() {
    long cPtr = IdaJavaJNI.plugin_info_t_entry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new plugin_t(cPtr, false);
  }

  public void setDllmem(idadll_t value) {
    IdaJavaJNI.plugin_info_t_dllmem_set(swigCPtr, this, idadll_t.getCPtr(value), value);
  }

  public idadll_t getDllmem() {
    long cPtr = IdaJavaJNI.plugin_info_t_dllmem_get(swigCPtr, this);
    return (cPtr == 0) ? null : new idadll_t(cPtr, false);
  }

  public void setFlags(int value) {
    IdaJavaJNI.plugin_info_t_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return IdaJavaJNI.plugin_info_t_flags_get(swigCPtr, this);
  }

  public plugin_info_t() {
    this(IdaJavaJNI.new_plugin_info_t(), true);
  }

}
