/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class process_info_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public process_info_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(process_info_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_process_info_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPid(int value) {
    IdaJavaJNI.process_info_t_pid_set(swigCPtr, this, value);
  }

  public int getPid() {
    return IdaJavaJNI.process_info_t_pid_get(swigCPtr, this);
  }

  public void setName(String value) {
    IdaJavaJNI.process_info_t_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return IdaJavaJNI.process_info_t_name_get(swigCPtr, this);
  }

  public process_info_t() {
    this(IdaJavaJNI.new_process_info_t(), true);
  }

}
