/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class pushreg_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public pushreg_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(pushreg_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_pushreg_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEa(long value) {
    IdaJavaJNI.pushreg_t_ea_set(swigCPtr, this, value);
  }

  public long getEa() {
    return IdaJavaJNI.pushreg_t_ea_get(swigCPtr, this);
  }

  public void setOff(long value) {
    IdaJavaJNI.pushreg_t_off_set(swigCPtr, this, value);
  }

  public long getOff() {
    return IdaJavaJNI.pushreg_t_off_get(swigCPtr, this);
  }

  public void setWidth(long value) {
    IdaJavaJNI.pushreg_t_width_set(swigCPtr, this, value);
  }

  public long getWidth() {
    return IdaJavaJNI.pushreg_t_width_get(swigCPtr, this);
  }

  public void setReg(short value) {
    IdaJavaJNI.pushreg_t_reg_set(swigCPtr, this, value);
  }

  public short getReg() {
    return IdaJavaJNI.pushreg_t_reg_get(swigCPtr, this);
  }

  public pushreg_t() {
    this(IdaJavaJNI.new_pushreg_t(), true);
  }

}
