/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class qvector_uchar {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public qvector_uchar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(qvector_uchar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_qvector_uchar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public qvector_uchar() {
    this(IdaJavaJNI.new_qvector_uchar__SWIG_0(), true);
  }

  public qvector_uchar(qvector_uchar x) {
    this(IdaJavaJNI.new_qvector_uchar__SWIG_1(qvector_uchar.getCPtr(x), x), true);
  }

  public void push_back(short x) {
    IdaJavaJNI.qvector_uchar_push_back__SWIG_0(swigCPtr, this, x);
  }

  public SWIGTYPE_p_unsigned_char push_back() {
    return new SWIGTYPE_p_unsigned_char(IdaJavaJNI.qvector_uchar_push_back__SWIG_1(swigCPtr, this), false);
  }

  public void pop_back() {
    IdaJavaJNI.qvector_uchar_pop_back(swigCPtr, this);
  }

  public long size() {
    return IdaJavaJNI.qvector_uchar_size(swigCPtr, this);
  }

  public boolean empty() {
    return IdaJavaJNI.qvector_uchar_empty(swigCPtr, this);
  }

  public short __aref__(long idx) {
    return IdaJavaJNI.qvector_uchar___aref____SWIG_0(swigCPtr, this, idx);
  }

  public short at(long idx) {
    return IdaJavaJNI.qvector_uchar_at__SWIG_0(swigCPtr, this, idx);
  }

  public short front() {
    return IdaJavaJNI.qvector_uchar_front__SWIG_0(swigCPtr, this);
  }

  public short back() {
    return IdaJavaJNI.qvector_uchar_back__SWIG_0(swigCPtr, this);
  }

  public void qclear() {
    IdaJavaJNI.qvector_uchar_qclear(swigCPtr, this);
  }

  public void clear() {
    IdaJavaJNI.qvector_uchar_clear(swigCPtr, this);
  }

  public qvector_uchar __assign__(qvector_uchar x) {
    return new qvector_uchar(IdaJavaJNI.qvector_uchar___assign__(swigCPtr, this, qvector_uchar.getCPtr(x), x), false);
  }

  public void resize(long s, short x) {
    IdaJavaJNI.qvector_uchar_resize__SWIG_0(swigCPtr, this, s, x);
  }

  public void resize(long s) {
    IdaJavaJNI.qvector_uchar_resize__SWIG_1(swigCPtr, this, s);
  }

  public void grow(short x) {
    IdaJavaJNI.qvector_uchar_grow__SWIG_0(swigCPtr, this, x);
  }

  public void grow() {
    IdaJavaJNI.qvector_uchar_grow__SWIG_1(swigCPtr, this);
  }

  public long capacity() {
    return IdaJavaJNI.qvector_uchar_capacity(swigCPtr, this);
  }

  public void reserve(long cnt) {
    IdaJavaJNI.qvector_uchar_reserve(swigCPtr, this, cnt);
  }

  public void move(SWIGTYPE_p_unsigned_char dst, SWIGTYPE_p_unsigned_char src, long cnt) {
    IdaJavaJNI.qvector_uchar_move(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(dst), SWIGTYPE_p_unsigned_char.getCPtr(src), cnt);
  }

  public void truncate() {
    IdaJavaJNI.qvector_uchar_truncate(swigCPtr, this);
  }

  public void swap(qvector_uchar r) {
    IdaJavaJNI.qvector_uchar_swap(swigCPtr, this, qvector_uchar.getCPtr(r), r);
  }

  public SWIGTYPE_p_unsigned_char extract() {
    long cPtr = IdaJavaJNI.qvector_uchar_extract(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void inject(SWIGTYPE_p_unsigned_char s, long len) {
    IdaJavaJNI.qvector_uchar_inject(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(s), len);
  }

  public boolean __eq__(qvector_uchar r) {
    return IdaJavaJNI.qvector_uchar___eq__(swigCPtr, this, qvector_uchar.getCPtr(r), r);
  }

  public boolean __ne__(qvector_uchar r) {
    return IdaJavaJNI.qvector_uchar___ne__(swigCPtr, this, qvector_uchar.getCPtr(r), r);
  }

  public SWIGTYPE_p_unsigned_char begin() {
    long cPtr = IdaJavaJNI.qvector_uchar_begin__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char end() {
    long cPtr = IdaJavaJNI.qvector_uchar_end__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char insert(SWIGTYPE_p_unsigned_char it, short x) {
    long cPtr = IdaJavaJNI.qvector_uchar_insert(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(it), x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char erase(SWIGTYPE_p_unsigned_char it) {
    long cPtr = IdaJavaJNI.qvector_uchar_erase__SWIG_0(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(it));
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char erase(SWIGTYPE_p_unsigned_char first, SWIGTYPE_p_unsigned_char last) {
    long cPtr = IdaJavaJNI.qvector_uchar_erase__SWIG_1(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(first), SWIGTYPE_p_unsigned_char.getCPtr(last));
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char find(short x) {
    long cPtr = IdaJavaJNI.qvector_uchar_find__SWIG_0(swigCPtr, this, x);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public boolean has(short x) {
    return IdaJavaJNI.qvector_uchar_has(swigCPtr, this, x);
  }

  public boolean add_unique(short x) {
    return IdaJavaJNI.qvector_uchar_add_unique(swigCPtr, this, x);
  }

  public boolean del(short x) {
    return IdaJavaJNI.qvector_uchar_del(swigCPtr, this, x);
  }

}
