/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class refinfo_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public refinfo_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(refinfo_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_refinfo_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTarget(long value) {
    IdaJavaJNI.refinfo_t_target_set(swigCPtr, this, value);
  }

  public long getTarget() {
    return IdaJavaJNI.refinfo_t_target_get(swigCPtr, this);
  }

  public void setBase(long value) {
    IdaJavaJNI.refinfo_t_base_set(swigCPtr, this, value);
  }

  public long getBase() {
    return IdaJavaJNI.refinfo_t_base_get(swigCPtr, this);
  }

  public void setTdelta(int value) {
    IdaJavaJNI.refinfo_t_tdelta_set(swigCPtr, this, value);
  }

  public int getTdelta() {
    return IdaJavaJNI.refinfo_t_tdelta_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    IdaJavaJNI.refinfo_t_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return IdaJavaJNI.refinfo_t_flags_get(swigCPtr, this);
  }

  public short type() {
    return IdaJavaJNI.refinfo_t_type(swigCPtr, this);
  }

  public boolean no_base_xref() {
    return IdaJavaJNI.refinfo_t_no_base_xref(swigCPtr, this);
  }

  public boolean is_pastend() {
    return IdaJavaJNI.refinfo_t_is_pastend(swigCPtr, this);
  }

  public boolean is_rvaoff() {
    return IdaJavaJNI.refinfo_t_is_rvaoff(swigCPtr, this);
  }

  public boolean is_custom() {
    return IdaJavaJNI.refinfo_t_is_custom(swigCPtr, this);
  }

  public boolean is_subtract() {
    return IdaJavaJNI.refinfo_t_is_subtract(swigCPtr, this);
  }

  public boolean is_signed() {
    return IdaJavaJNI.refinfo_t_is_signed(swigCPtr, this);
  }

  public void set_type(short t) {
    IdaJavaJNI.refinfo_t_set_type(swigCPtr, this, t);
  }

  public void init(long reft_and_flags, long _base, long _target, int _tdelta) {
    IdaJavaJNI.refinfo_t_init__SWIG_0(swigCPtr, this, reft_and_flags, _base, _target, _tdelta);
  }

  public void init(long reft_and_flags, long _base, long _target) {
    IdaJavaJNI.refinfo_t_init__SWIG_1(swigCPtr, this, reft_and_flags, _base, _target);
  }

  public void init(long reft_and_flags, long _base) {
    IdaJavaJNI.refinfo_t_init__SWIG_2(swigCPtr, this, reft_and_flags, _base);
  }

  public void init(long reft_and_flags) {
    IdaJavaJNI.refinfo_t_init__SWIG_3(swigCPtr, this, reft_and_flags);
  }

  public refinfo_t() {
    this(IdaJavaJNI.new_refinfo_t(), true);
  }

}
