/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class reg_info_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public reg_info_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(reg_info_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_reg_info_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setReg(int value) {
    IdaJavaJNI.reg_info_t_reg_set(swigCPtr, this, value);
  }

  public int getReg() {
    return IdaJavaJNI.reg_info_t_reg_get(swigCPtr, this);
  }

  public void setSize(int value) {
    IdaJavaJNI.reg_info_t_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return IdaJavaJNI.reg_info_t_size_get(swigCPtr, this);
  }

  public boolean __eq__(reg_info_t r) {
    return IdaJavaJNI.reg_info_t___eq__(swigCPtr, this, reg_info_t.getCPtr(r), r);
  }

  public boolean __ne__(reg_info_t r) {
    return IdaJavaJNI.reg_info_t___ne__(swigCPtr, this, reg_info_t.getCPtr(r), r);
  }

  public reg_info_t() {
    this(IdaJavaJNI.new_reg_info_t(), true);
  }

}
