/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class regvar_t extends area_t {
  private long swigCPtr;

  public regvar_t(long cPtr, boolean cMemoryOwn) {
    super(IdaJavaJNI.regvar_t_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(regvar_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_regvar_t(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setCanon(String value) {
    IdaJavaJNI.regvar_t_canon_set(swigCPtr, this, value);
  }

  public String getCanon() {
    return IdaJavaJNI.regvar_t_canon_get(swigCPtr, this);
  }

  public void setUser(String value) {
    IdaJavaJNI.regvar_t_user_set(swigCPtr, this, value);
  }

  public String getUser() {
    return IdaJavaJNI.regvar_t_user_get(swigCPtr, this);
  }

  public void setCmt(String value) {
    IdaJavaJNI.regvar_t_cmt_set(swigCPtr, this, value);
  }

  public String getCmt() {
    return IdaJavaJNI.regvar_t_cmt_get(swigCPtr, this);
  }

  public regvar_t() {
    this(IdaJavaJNI.new_regvar_t(), true);
  }

}
