/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class reloc_info_t extends bytevec_t {
  private long swigCPtr;

  public reloc_info_t(long cPtr, boolean cMemoryOwn) {
    super(IdaJavaJNI.reloc_info_t_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(reloc_info_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_reloc_info_t(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public reloc_info_t() {
    this(IdaJavaJNI.new_reloc_info_t(), true);
  }

}
