/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class row_info_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public row_info_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(row_info_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_row_info_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNodes(SWIGTYPE_p_intseq_t value) {
    IdaJavaJNI.row_info_t_nodes_set(swigCPtr, this, SWIGTYPE_p_intseq_t.getCPtr(value));
  }

  public SWIGTYPE_p_intseq_t getNodes() {
    return new SWIGTYPE_p_intseq_t(IdaJavaJNI.row_info_t_nodes_get(swigCPtr, this), true);
  }

  public void setTop(int value) {
    IdaJavaJNI.row_info_t_top_set(swigCPtr, this, value);
  }

  public int getTop() {
    return IdaJavaJNI.row_info_t_top_get(swigCPtr, this);
  }

  public void setBottom(int value) {
    IdaJavaJNI.row_info_t_bottom_set(swigCPtr, this, value);
  }

  public int getBottom() {
    return IdaJavaJNI.row_info_t_bottom_get(swigCPtr, this);
  }

  public int height() {
    return IdaJavaJNI.row_info_t_height(swigCPtr, this);
  }

  public row_info_t() {
    this(IdaJavaJNI.new_row_info_t(), true);
  }

}
