/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class screen_graph_selection_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public screen_graph_selection_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(screen_graph_selection_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_screen_graph_selection_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean has(selection_item_t item) {
    return IdaJavaJNI.screen_graph_selection_t_has(swigCPtr, this, selection_item_t.getCPtr(item), item);
  }

  public void add(screen_graph_selection_t s) {
    IdaJavaJNI.screen_graph_selection_t_add(swigCPtr, this, screen_graph_selection_t.getCPtr(s), s);
  }

  public void sub(screen_graph_selection_t s) {
    IdaJavaJNI.screen_graph_selection_t_sub(swigCPtr, this, screen_graph_selection_t.getCPtr(s), s);
  }

  public void add_node(int n) {
    IdaJavaJNI.screen_graph_selection_t_add_node(swigCPtr, this, n);
  }

  public void del_node(int n) {
    IdaJavaJNI.screen_graph_selection_t_del_node(swigCPtr, this, n);
  }

  public void add_point(edge_t e, int idx) {
    IdaJavaJNI.screen_graph_selection_t_add_point(swigCPtr, this, edge_t.getCPtr(e), e, idx);
  }

  public void del_point(edge_t e, int idx) {
    IdaJavaJNI.screen_graph_selection_t_del_point(swigCPtr, this, edge_t.getCPtr(e), e, idx);
  }

  public screen_graph_selection_t() {
    this(IdaJavaJNI.new_screen_graph_selection_t(), true);
  }

}
