/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class segment_t extends area_t {
  private long swigCPtr;

  public segment_t(long cPtr, boolean cMemoryOwn) {
    super(IdaJavaJNI.segment_t_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(segment_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_segment_t(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public segment_t() {
    this(IdaJavaJNI.new_segment_t(), true);
  }

  public void setName(long value) {
    IdaJavaJNI.segment_t_name_set(swigCPtr, this, value);
  }

  public long getName() {
    return IdaJavaJNI.segment_t_name_get(swigCPtr, this);
  }

  public void setSclass(long value) {
    IdaJavaJNI.segment_t_sclass_set(swigCPtr, this, value);
  }

  public long getSclass() {
    return IdaJavaJNI.segment_t_sclass_get(swigCPtr, this);
  }

  public void setOrgbase(long value) {
    IdaJavaJNI.segment_t_orgbase_set(swigCPtr, this, value);
  }

  public long getOrgbase() {
    return IdaJavaJNI.segment_t_orgbase_get(swigCPtr, this);
  }

  public void setAlign(short value) {
    IdaJavaJNI.segment_t_align_set(swigCPtr, this, value);
  }

  public short getAlign() {
    return IdaJavaJNI.segment_t_align_get(swigCPtr, this);
  }

  public void setComb(short value) {
    IdaJavaJNI.segment_t_comb_set(swigCPtr, this, value);
  }

  public short getComb() {
    return IdaJavaJNI.segment_t_comb_get(swigCPtr, this);
  }

  public void setPerm(short value) {
    IdaJavaJNI.segment_t_perm_set(swigCPtr, this, value);
  }

  public short getPerm() {
    return IdaJavaJNI.segment_t_perm_get(swigCPtr, this);
  }

  public void setBitness(short value) {
    IdaJavaJNI.segment_t_bitness_set(swigCPtr, this, value);
  }

  public short getBitness() {
    return IdaJavaJNI.segment_t_bitness_get(swigCPtr, this);
  }

  public boolean use32() {
    return IdaJavaJNI.segment_t_use32(swigCPtr, this);
  }

  public boolean use64() {
    return IdaJavaJNI.segment_t_use64(swigCPtr, this);
  }

  public int abits() {
    return IdaJavaJNI.segment_t_abits(swigCPtr, this);
  }

  public int abytes() {
    return IdaJavaJNI.segment_t_abytes(swigCPtr, this);
  }

  public void setFlags(int value) {
    IdaJavaJNI.segment_t_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return IdaJavaJNI.segment_t_flags_get(swigCPtr, this);
  }

  public boolean comorg() {
    return IdaJavaJNI.segment_t_comorg(swigCPtr, this);
  }

  public void set_comorg() {
    IdaJavaJNI.segment_t_set_comorg(swigCPtr, this);
  }

  public void clr_comorg() {
    IdaJavaJNI.segment_t_clr_comorg(swigCPtr, this);
  }

  public boolean ob_ok() {
    return IdaJavaJNI.segment_t_ob_ok(swigCPtr, this);
  }

  public void set_ob_ok() {
    IdaJavaJNI.segment_t_set_ob_ok(swigCPtr, this);
  }

  public void clr_ob_ok() {
    IdaJavaJNI.segment_t_clr_ob_ok(swigCPtr, this);
  }

  public boolean is_visible_segm() {
    return IdaJavaJNI.segment_t_is_visible_segm(swigCPtr, this);
  }

  public void set_visible_segm(boolean visible) {
    IdaJavaJNI.segment_t_set_visible_segm(swigCPtr, this, visible);
  }

  public boolean is_debugger_segm() {
    return IdaJavaJNI.segment_t_is_debugger_segm(swigCPtr, this);
  }

  public void set_debugger_segm(boolean debseg) {
    IdaJavaJNI.segment_t_set_debugger_segm(swigCPtr, this, debseg);
  }

  public boolean is_loader_segm() {
    return IdaJavaJNI.segment_t_is_loader_segm(swigCPtr, this);
  }

  public void set_loader_segm(boolean ldrseg) {
    IdaJavaJNI.segment_t_set_loader_segm(swigCPtr, this, ldrseg);
  }

  public boolean is_hidden_segtype() {
    return IdaJavaJNI.segment_t_is_hidden_segtype(swigCPtr, this);
  }

  public void set_hidden_segtype(boolean hide) {
    IdaJavaJNI.segment_t_set_hidden_segtype(swigCPtr, this, hide);
  }

  public boolean is_ephemeral_segm() {
    return IdaJavaJNI.segment_t_is_ephemeral_segm(swigCPtr, this);
  }

  public void setSel(long value) {
    IdaJavaJNI.segment_t_sel_set(swigCPtr, this, value);
  }

  public long getSel() {
    return IdaJavaJNI.segment_t_sel_get(swigCPtr, this);
  }

  public void setDefsr(long[] value) {
    IdaJavaJNI.segment_t_defsr_set(swigCPtr, this, value);
  }

  public long[] getDefsr() {
    return IdaJavaJNI.segment_t_defsr_get(swigCPtr, this);
  }

  public void setType(short value) {
    IdaJavaJNI.segment_t_type_set(swigCPtr, this, value);
  }

  public short getType() {
    return IdaJavaJNI.segment_t_type_get(swigCPtr, this);
  }

  public void setColor(long value) {
    IdaJavaJNI.segment_t_color_set(swigCPtr, this, value);
  }

  public long getColor() {
    return IdaJavaJNI.segment_t_color_get(swigCPtr, this);
  }

  public int update() {
    return IdaJavaJNI.segment_t_update(swigCPtr, this);
  }

}
