/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class simple_edge_typer_t extends edge_typer_t {
  private long swigCPtr;

  public simple_edge_typer_t(long cPtr, boolean cMemoryOwn) {
    super(IdaJavaJNI.simple_edge_typer_t_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(simple_edge_typer_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_simple_edge_typer_t(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setEdge_types(SWIGTYPE_p_std__mapT_edge_t_edge_type_t_t value) {
    IdaJavaJNI.simple_edge_typer_t_edge_types_set(swigCPtr, this, SWIGTYPE_p_std__mapT_edge_t_edge_type_t_t.getCPtr(value));
  }

  public SWIGTYPE_p_std__mapT_edge_t_edge_type_t_t getEdge_types() {
    return new SWIGTYPE_p_std__mapT_edge_t_edge_type_t_t(IdaJavaJNI.simple_edge_typer_t_edge_types_get(swigCPtr, this), true);
  }

  public void reset() {
    IdaJavaJNI.simple_edge_typer_t_reset(swigCPtr, this);
  }

  public SWIGTYPE_p_edge_type_t edge_type(int i, int j) {
    return new SWIGTYPE_p_edge_type_t(IdaJavaJNI.simple_edge_typer_t_edge_type(swigCPtr, this, i, j), false);
  }

  public simple_edge_typer_t() {
    this(IdaJavaJNI.new_simple_edge_typer_t(), true);
  }

}
