/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class stkpnt_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public stkpnt_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(stkpnt_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_stkpnt_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setEa(long value) {
    IdaJavaJNI.stkpnt_t_ea_set(swigCPtr, this, value);
  }

  public long getEa() {
    return IdaJavaJNI.stkpnt_t_ea_get(swigCPtr, this);
  }

  public void setSpd(int value) {
    IdaJavaJNI.stkpnt_t_spd_set(swigCPtr, this, value);
  }

  public int getSpd() {
    return IdaJavaJNI.stkpnt_t_spd_get(swigCPtr, this);
  }

  public boolean __lt__(stkpnt_t r) {
    return IdaJavaJNI.stkpnt_t___lt__(swigCPtr, this, stkpnt_t.getCPtr(r), r);
  }

  public stkpnt_t() {
    this(IdaJavaJNI.new_stkpnt_t(), true);
  }

}
