/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class strpath_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public strpath_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(strpath_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_strpath_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLen(int value) {
    IdaJavaJNI.strpath_t_len_set(swigCPtr, this, value);
  }

  public int getLen() {
    return IdaJavaJNI.strpath_t_len_get(swigCPtr, this);
  }

  public void setIds(long[] value) {
    IdaJavaJNI.strpath_t_ids_set(swigCPtr, this, value);
  }

  public long[] getIds() {
    return IdaJavaJNI.strpath_t_ids_get(swigCPtr, this);
  }

  public void setDelta(int value) {
    IdaJavaJNI.strpath_t_delta_set(swigCPtr, this, value);
  }

  public int getDelta() {
    return IdaJavaJNI.strpath_t_delta_get(swigCPtr, this);
  }

  public strpath_t() {
    this(IdaJavaJNI.new_strpath_t(), true);
  }

}
