/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class SWIGTYPE_p_f_unsigned_int_int_p_q_const__func_type_info_t_int_p_q_const__regobjs_t_p_relobj_t_p_regobjs_t_p__qstring__char___p_debug_event_t_int__unsigned_int {
  private long swigCPtr;

  protected SWIGTYPE_p_f_unsigned_int_int_p_q_const__func_type_info_t_int_p_q_const__regobjs_t_p_relobj_t_p_regobjs_t_p__qstring__char___p_debug_event_t_int__unsigned_int(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_unsigned_int_int_p_q_const__func_type_info_t_int_p_q_const__regobjs_t_p_relobj_t_p_regobjs_t_p__qstring__char___p_debug_event_t_int__unsigned_int() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_unsigned_int_int_p_q_const__func_type_info_t_int_p_q_const__regobjs_t_p_relobj_t_p_regobjs_t_p__qstring__char___p_debug_event_t_int__unsigned_int obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

