/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class SWIGTYPE_p_f_p_q_const__idc_value_t_p_q_const__char_int_a___q_const__idc_value_t_p_idc_value_t_p_char_size_t__bool {
  private long swigCPtr;

  protected SWIGTYPE_p_f_p_q_const__idc_value_t_p_q_const__char_int_a___q_const__idc_value_t_p_idc_value_t_p_char_size_t__bool(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_q_const__idc_value_t_p_q_const__char_int_a___q_const__idc_value_t_p_idc_value_t_p_char_size_t__bool() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_q_const__idc_value_t_p_q_const__char_int_a___q_const__idc_value_t_p_idc_value_t_p_char_size_t__bool obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

