/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class text_options_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public text_options_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(text_options_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_text_options_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setText(dual_text_options_t value) {
    IdaJavaJNI.text_options_t_text_set(swigCPtr, this, dual_text_options_t.getCPtr(value), value);
  }

  public dual_text_options_t getText() {
    long cPtr = IdaJavaJNI.text_options_t_text_get(swigCPtr, this);
    return (cPtr == 0) ? null : new dual_text_options_t(cPtr, false);
  }

  public void setGraph(dual_text_options_t value) {
    IdaJavaJNI.text_options_t_graph_set(swigCPtr, this, dual_text_options_t.getCPtr(value), value);
  }

  public dual_text_options_t getGraph() {
    long cPtr = IdaJavaJNI.text_options_t_graph_get(swigCPtr, this);
    return (cPtr == 0) ? null : new dual_text_options_t(cPtr, false);
  }

  public text_options_t() {
    this(IdaJavaJNI.new_text_options_t(), true);
  }

}
