/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public enum tribyte_order_t {
  tbo_123,
  tbo_132,
  tbo_213,
  tbo_231,
  tbo_312,
  tbo_321;

  public final int swigValue() {
    return swigValue;
  }

  public static tribyte_order_t swigToEnum(int swigValue) {
    tribyte_order_t[] swigValues = tribyte_order_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (tribyte_order_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + tribyte_order_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private tribyte_order_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private tribyte_order_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private tribyte_order_t(tribyte_order_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

