/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class user_graph_place_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public user_graph_place_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(user_graph_place_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_user_graph_place_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNode(int value) {
    IdaJavaJNI.user_graph_place_t_node_set(swigCPtr, this, value);
  }

  public int getNode() {
    return IdaJavaJNI.user_graph_place_t_node_get(swigCPtr, this);
  }

}
