/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class vxd_info {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public vxd_info(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(vxd_info obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_vxd_info(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSp_off(int value) {
    IdaJavaJNI.vxd_info_sp_off_set(swigCPtr, this, value);
  }

  public int getSp_off() {
    return IdaJavaJNI.vxd_info_sp_off_get(swigCPtr, this);
  }

  public void setPrm_pos(int value) {
    IdaJavaJNI.vxd_info_prm_pos_set(swigCPtr, this, value);
  }

  public int getPrm_pos() {
    return IdaJavaJNI.vxd_info_prm_pos_get(swigCPtr, this);
  }

  public void setCmt_pos(int value) {
    IdaJavaJNI.vxd_info_cmt_pos_set(swigCPtr, this, value);
  }

  public int getCmt_pos() {
    return IdaJavaJNI.vxd_info_cmt_pos_get(swigCPtr, this);
  }

  public void setStrings(String value) {
    IdaJavaJNI.vxd_info_strings_set(swigCPtr, this, value);
  }

  public String getStrings() {
    return IdaJavaJNI.vxd_info_strings_get(swigCPtr, this);
  }

  public vxd_info() {
    this(IdaJavaJNI.new_vxd_info(), true);
  }

}
