/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package de.blichmann.idajava.natives;

public class xrefblk_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public xrefblk_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(xrefblk_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        IdaJavaJNI.delete_xrefblk_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFrom(long value) {
    IdaJavaJNI.xrefblk_t_from_set(swigCPtr, this, value);
  }

  public long getFrom() {
    return IdaJavaJNI.xrefblk_t_from_get(swigCPtr, this);
  }

  public void setTo(long value) {
    IdaJavaJNI.xrefblk_t_to_set(swigCPtr, this, value);
  }

  public long getTo() {
    return IdaJavaJNI.xrefblk_t_to_get(swigCPtr, this);
  }

  public void setIscode(short value) {
    IdaJavaJNI.xrefblk_t_iscode_set(swigCPtr, this, value);
  }

  public short getIscode() {
    return IdaJavaJNI.xrefblk_t_iscode_get(swigCPtr, this);
  }

  public void setType(short value) {
    IdaJavaJNI.xrefblk_t_type_set(swigCPtr, this, value);
  }

  public short getType() {
    return IdaJavaJNI.xrefblk_t_type_get(swigCPtr, this);
  }

  public void setUser(short value) {
    IdaJavaJNI.xrefblk_t_user_set(swigCPtr, this, value);
  }

  public short getUser() {
    return IdaJavaJNI.xrefblk_t_user_get(swigCPtr, this);
  }

  public boolean first_from(long from, int flags) {
    return IdaJavaJNI.xrefblk_t_first_from(swigCPtr, this, from, flags);
  }

  public boolean next_from() {
    return IdaJavaJNI.xrefblk_t_next_from__SWIG_0(swigCPtr, this);
  }

  public boolean first_to(long to, int flags) {
    return IdaJavaJNI.xrefblk_t_first_to(swigCPtr, this, to, flags);
  }

  public boolean next_to() {
    return IdaJavaJNI.xrefblk_t_next_to__SWIG_0(swigCPtr, this);
  }

  public boolean next_from(long from, long _to, int flags) {
    return IdaJavaJNI.xrefblk_t_next_from__SWIG_1(swigCPtr, this, from, _to, flags);
  }

  public boolean next_to(long _from, long to, int flags) {
    return IdaJavaJNI.xrefblk_t_next_to__SWIG_1(swigCPtr, this, _from, to, flags);
  }

  public xrefblk_t() {
    this(IdaJavaJNI.new_xrefblk_t(), true);
  }

}
